const Auth={
 async loginWithCredentials(type,account,password){const r=await fetch('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},cache:'no-store',body:JSON.stringify({type,account,password})});let d=null;try{d=await r.json()}catch{}if(!r.ok||!d?.success){const e=new Error(d?.error||'账号或密码错误');e.status=r.status;throw e}const u=d.user||{},route=type==='admin'?'admin':this.formatRouteCode(u.route);this.login(route,u.name||(type==='admin'?'管理员':'司机'));localStorage.setItem('currentUserRole',u.role||(type==='admin'?'admin':'driver'));if(d.sessionToken)localStorage.setItem('sessionToken',d.sessionToken);return u},
 getSessionToken(){return localStorage.getItem('sessionToken')||''},getAuthHeaders(extra={}){const h={...extra},t=this.getSessionToken();if(t)h.Authorization=`Bearer ${t}`;return h},
 async getUsers(){try{const u=await this.fetchUsersFromUpstash();if(u){localStorage.setItem('admin_users',JSON.stringify(u));return u}}catch(e){console.warn('获取用户数据失败，使用本地缓存')}return this.getLocalUsers()},
 getLocalUsers(){try{const d=localStorage.getItem('admin_users');return d?JSON.parse(d):[]}catch{return[]}},
 async fetchUsersFromUpstash(){const r=await fetch('/api/users',{cache:'no-store',headers:this.getAuthHeaders()});if(!r.ok)throw Error('Failed to fetch users');const d=await r.json();let u=d.users;if(typeof u==='string')u=JSON.parse(u);return Array.isArray(u)?u:[]},
 async saveUsersToUpstash(users){const r=await fetch('/api/users',{method:'POST',headers:this.getAuthHeaders({'Content-Type':'application/json'}),body:JSON.stringify({users})});if(!r.ok)throw Error('Failed to save users')},
 async saveUsers(users){return this.saveUsersToUpstash(users)},
 async findUserByRoute(route){const u=await this.getUsers(),f=this.formatRouteCode(route);return u.find(x=>x.route===f)||null},async findAdminByName(name){const u=await this.getUsers();return u.find(x=>x.role==='admin'&&x.name===name)||null},async isRouteRegistered(route){return!!(await this.findUserByRoute(route))},
 async createUser(route,password,role='driver',name=''){const f=this.formatRouteCode(route);if(await this.findUserByRoute(f))return null;const u=await this.getUsers(),id=u.reduce((m,x)=>Math.max(m,x.id||0),0)+1,n={id,name:name||'',route:f,password,role,createdAt:new Date().toISOString()};u.push(n);await this.saveUsersToUpstash(u);return n},
 async updateUser(route,updates){const f=this.formatRouteCode(route),u=await this.getUsers(),i=u.findIndex(x=>x.route===f);if(i<0)return null;u[i]={...u[i],...updates};await this.saveUsersToUpstash(u);return u[i]},async deleteUser(route){const f=this.formatRouteCode(route),u=(await this.getUsers()).filter(x=>x.route!==f);await this.saveUsersToUpstash(u)},
 getUserDataKey(route){return`user_data_${this.formatRouteCode(route)}`},getUserOrderData(route){try{const d=localStorage.getItem(this.getUserDataKey(route));return d?JSON.parse(d):null}catch{return null}},saveUserOrderData(route,data){localStorage.setItem(this.getUserDataKey(route),JSON.stringify(data))},clearUserOrderData(route){localStorage.removeItem(this.getUserDataKey(route))},
 checkAuth(){const ok=localStorage.getItem('loginStatus')==='true'&&localStorage.getItem('currentRoute')&&this.getSessionToken();if(ok)return true;const p=location.pathname.split('/').pop();if(['index.html','login.html',''].includes(p))return false;location.href=location.pathname.includes('/pages/')?'../index.html':'index.html';return false},getCurrentRoute(){return localStorage.getItem('currentRoute')||''},getCurrentUser(){return localStorage.getItem('currentUser')||'司机'},
 login(route,user='司机'){this.clearSessionCache();const f=route==='admin'?'admin':this.formatRouteCode(route);localStorage.setItem('loginStatus','true');localStorage.setItem('currentRoute',f);localStorage.setItem('currentUser',user);const d=this.getUserOrderData(f);if(d){if(d.today_orders)localStorage.setItem('today_orders',JSON.stringify(d.today_orders));if(d.today_vehicle)localStorage.setItem('today_vehicle',d.today_vehicle);if(d.base_data)localStorage.setItem('base_data',JSON.stringify(d.base_data));if(d.delivery_history)localStorage.setItem('delivery_history',JSON.stringify(d.delivery_history));if(d.route_cache)localStorage.setItem(`route_cache_${f}`,JSON.stringify(d.route_cache))}},
 logout(){const r=this.getCurrentRoute();if(r)this.saveUserOrderData(r,{today_orders:this.getTodayOrders(),today_vehicle:localStorage.getItem('today_vehicle')||'',base_data:this.getBaseData(),delivery_history:this.getDeliveryHistory(),route_cache:this.getCachedRouteData(r),lastLogin:new Date().toISOString()});this.clearSessionCache();['loginStatus','currentRoute','currentUser','currentUserRole','sessionToken'].forEach(k=>localStorage.removeItem(k));location.href=location.pathname.includes('/pages/')?'../index.html':'index.html'},
 clearSessionCache(){['today_orders','history_view_data','base_data'].forEach(k=>localStorage.removeItem(k));const r=this.getCurrentRoute();if(r)localStorage.removeItem(`route_cache_${r}`)},getTodayOrders(){try{const d=localStorage.getItem('today_orders');return d?JSON.parse(d):null}catch{return null}},getBaseData(){try{const d=localStorage.getItem('base_data');return d?JSON.parse(d):null}catch{return null}},getDeliveryHistory(){try{const d=localStorage.getItem('delivery_history');return d?JSON.parse(d):null}catch{return null}},getCachedRouteData(route){try{const d=localStorage.getItem(`route_cache_${this.formatRouteCode(route)}`);return d?JSON.parse(d):null}catch{return null}},
 formatRouteCode(input){if(!input)return'';const c=String(input).trim(),m=c.match(/(\d+)号线/);if(m)return String(parseInt(m[1])).padStart(2,'0')+'号线';const n=c.match(/^(\d+)$/);if(n)return String(parseInt(n[1])).padStart(2,'0')+'号线';return c},isValidRouteCode(c){return/^\d{2,}号线$/.test(c)},
 async createRoute(route,password,role='driver',name=''){const f=this.formatRouteCode(route);if(!this.isValidRouteCode(f)||await this.findUserByRoute(f))return null;const u=await this.createUser(f,password,role,name);if(!u)return null;const stores=[{code:'01',name:'新门店_01',nav:''},{code:'02',name:'新门店_02',nav:''},{code:'03',name:'新门店_03',nav:''}],data={route:f,stores,createdAt:new Date().toISOString()};this.cacheRouteData(f,data);localStorage.setItem('base_data',JSON.stringify(stores));try{await fetch(`/api/routes?route=${encodeURIComponent(f)}`,{method:'PUT',headers:this.getAuthHeaders({'Content-Type':'application/json'}),body:JSON.stringify({stores})})}catch{}return data},
 cacheRouteData(route,data){const f=this.formatRouteCode(route);localStorage.setItem(`route_cache_${f}`,JSON.stringify(data));const u=this.getUserOrderData(f);if(u){u.route_cache=data;this.saveUserOrderData(f,u)}},addLog(action,detail){try{const l=JSON.parse(localStorage.getItem('admin_logs')||'[]');l.unshift({id:Date.now(),time:new Date().toLocaleString(),action,detail,user:this.getCurrentRoute()||'system'});if(l.length>100)l.length=100;localStorage.setItem('admin_logs',JSON.stringify(l))}catch{}}
};

// 管理后台兼容入口：修复 T1 admin.html 缺失 openUserManagement 导致管理脚本初始化中断。
window.openUserManagement=async function(){
 const dialog=document.getElementById('userDialog'),list=document.getElementById('userList');
 if(dialog)dialog.classList.add('active'); if(!list)return;
 list.innerHTML='<div class="admin-empty">⏳ 正在加载用户数据...</div>';
 try{const users=await Auth.getUsers();if(!users.length){list.innerHTML='<div class="admin-empty">暂无用户</div>';return;}
 const roleMap={admin:'管理员',driver:'司机',delivery:'配送'},roleClass={admin:'admin',driver:'driver',delivery:'delivery'};
 list.innerHTML=users.sort((a,b)=>a.role==='admin'?-1:b.role==='admin'?1:(a.id||0)-(b.id||0)).map(u=>`<div class="admin-list-item"><div class="info"><div class="name">${u.name||'(未命名)'}</div><div class="sub">${u.route||''} · <span class="role-badge ${roleClass[u.role]||'driver'}">${roleMap[u.role]||'司机'}</span></div></div><div class="actions"><button class="edit-btn" onclick="editUser(${u.id})">编辑</button>${u.role==='admin'?'':`<button class="del-btn" onclick="deleteUser(${u.id})">删除</button>`}</div></div>`).join('');
 }catch(e){list.innerHTML=`<div class="admin-empty">加载失败：${e.message}</div>`;}
};
document.addEventListener('DOMContentLoaded',()=>{const p=location.pathname.split('/').pop();if(!['index.html','login.html',''].includes(p))Auth.checkAuth()});window.Auth=Auth;
