/* 天友智配One OCR V4核心模块：长运单区域二次识别 */
(function(){'use strict';
const SDK='https://cdn.jsdelivr.net/npm/@paddleocr/paddleocr-js@0.4.2/+esm';
let sdkPromise=null,ocr=null;
const $=id=>document.getElementById(id);
const route=()=>window.Auth?.getCurrentRoute?.()||'';
const norm=v=>String(v??'').replace(/\r\n/g,'\n').replace(/\r/g,'\n').replace(/[\u200B-\u200D\uFEFF]/g,'').trim();
const line=v=>String(v??'').replace(/[→＞》➜➤⇒]/g,'->').replace(/-\s*>/g,'->').replace(/[“”‘’]/g,'').replace(/[ \t]+/g,' ').trim();
const minX=p=>p?.length?Math.min(...p.map(x=>+x?.[0]||0)):0;
const minY=p=>p?.length?Math.min(...p.map(x=>+x?.[1]||0)):0;
const maxY=p=>p?.length?Math.max(...p.map(x=>+x?.[1]||0)):0;
const h=p=>Math.max(1,maxY(p)-minY(p));
const cy=x=>(minY(x.poly)+maxY(x.poly))/2;
function order(a,b){const d=Math.abs(cy(a)-cy(b)),t=Math.max(h(a.poly),h(b.poly))*.62;return d<=t?minX(a.poly)-minX(b.poly):cy(a)-cy(b)}
async function getOCR(){if(ocr)return ocr;if(sdkPromise)return sdkPromise;sdkPromise=(async()=>{const m=await import(SDK);const C=m.PaddleOCR||m.default?.PaddleOCR||m.default;if(!C?.create)throw Error('PaddleOCR加载失败');ocr=await C.create({lang:'ch',ocrVersion:'PP-OCRv5',worker:true,textDetectionBatchSize:2,textRecognitionBatchSize:6,ortOptions:{backend:'wasm',numThreads:window.crossOriginIsolated?2:1,simd:true}});return ocr})().catch(e=>{sdkPromise=null;throw e});return sdkPromise}
async function predict(input){const r=(await getOCR()).predict(input,{textRecScoreThresh:0})?.[0];if(!r?.items?.length)throw Error('PaddleOCR未检测到文字');return{items:r.items.map((x,i)=>({id:i,text:line(x.text),score:Number(x.score),poly:Array.isArray(x.poly)?x.poly:[]})).filter(x=>x.text).sort(order),metrics:r.metrics||{}}}
async function image(file){const u=URL.createObjectURL(file);try{return await new Promise((ok,no)=>{const i=new Image();i.onload=()=>ok(i);i.onerror=()=>no(Error('图片读取失败'));i.src=u})}finally{URL.revokeObjectURL(u)}}
async function deliveryCrop(file,items,header){const im=await image(file),W=im.naturalWidth,H=im.naturalHeight,related=items.filter(x=>x.poly.length&&minY(x.poly)>=minY(header.poly));if(!related.length)return null;const top=Math.max(0,minY(header.poly)-h(header.poly)*2),left=Math.max(0,Math.min(...related.map(minX))-Math.max(24,W*.012)),right=Math.min(W,Math.max(...related.map(x=>Math.max(...x.poly.map(p=>+p?.[0]||0))))+Math.max(24,W*.012)),w=Math.max(1,right-left),scale=Math.max(1,Math.min(2.8,Math.max(1800,w*1.8)/w)),c=document.createElement('canvas');c.width=Math.round(w*scale);c.height=Math.round((H-top)*scale);const ctx=c.getContext('2d',{alpha:false});ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';ctx.fillStyle='#fff';ctx.fillRect(0,0,c.width,c.height);ctx.drawImage(im,left,top,w,H-top,0,0,c.width,c.height);return{blob:await new Promise(r=>c.toBlob(r,'image/jpeg',.97)),left,top,scale}}
function abs(x,r){return{...x,poly:x.poly.map(p=>[(+p[0]/r.scale)+r.left,(+p[1]/r.scale)+r.top])}}
function overlap(a,b){if(!a.poly.length||!b.poly.length)return 0;const ax0=minX(a.poly),ax1=Math.max(...a.poly.map(p=>+p[0]||0)),ay0=minY(a.poly),ay1=maxY(a.poly),bx0=minX(b.poly),bx1=Math.max(...b.poly.map(p=>+p[0]||0)),by0=minY(b.poly),by1=maxY(b.poly),ox=Math.max(0,Math.min(ax1,bx1)-Math.max(ax0,bx0)),oy=Math.max(0,Math.min(ay1,by1)-Math.max(ay0,by0));return ox*oy/Math.max(1,Math.min((ax1-ax0)*(ay1-ay0),(bx1-bx0)*(by1-by0)))}
function mergeSpatial(a,b){const out=[],used=new Set();for(const x of a){let hit=-1,best=0;for(let i=0;i<b.length;i++){if(used.has(i))continue;const q=overlap(x,b[i]);if(q>.35&&q>best){best=q;hit=i}}if(hit>=0){const y=b[hit];used.add(hit);out.push({...x,text:y.text.length>x.text.length?y.text:x.text,score:Math.max(x.score||0,y.score||0)})}else out.push(x)}b.forEach((x,i)=>{if(!used.has(i))out.push(x)});return out.sort(order).map((x,i)=>({...x,id:i}))}
async function cropLine(file,item){const im=await image(file),xs=item.poly.map(p=>+p[0]||0),ys=item.poly.map(p=>+p[1]||0),px=Math.max(22,(Math.max(...xs)-Math.min(...xs))*.06),py=Math.max(18,(Math.max(...ys)-Math.min(...ys))*.65),l=Math.max(0,Math.floor(Math.min(...xs)-px)),t=Math.max(0,Math.floor(Math.min(...ys)-py)),r=Math.min(im.naturalWidth,Math.ceil(Math.max(...xs)+px)),b=Math.min(im.naturalHeight,Math.ceil(Math.max(...ys)+py)),w=Math.max(1,r-l),hh=Math.max(1,b-t),s=Math.min(3,Math.max(2,1800/w)),c=document.createElement('canvas');c.width=Math.round(w*s);c.height=Math.round(hh*s);const ctx=c.getContext('2d',{alpha:false});ctx.fillStyle='#fff';ctx.fillRect(0,0,c.width,c.height);ctx.filter='grayscale(1) contrast(1.12) brightness(1.02)';ctx.drawImage(im,l,t,w,hh,0,0,c.width,c.height);ctx.filter='none';return c.toDataURL('image/jpeg',.97)}
async function serverOCR(images){const r=await fetch('/api/ocr',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'same-origin',cache:'no-store',body:JSON.stringify({images,route:route(),mode:'line'})}),d=await r.json().catch(()=>({}));if(!r.ok||!d.success)throw Error(d.error||`OCR请求失败(${r.status})`);return d.data||{}}
function single(v){return norm(v).split('\n').map(line).filter(x=>/[\u4e00-\u9fffA-Za-z0-9]/.test(x)&&x.length>=2).sort((a,b)=>b.length-a.length)[0]||''}
async function lowReview(file,items){const map=new Map(),targets=items.filter(x=>Number.isFinite(x.score)&&x.score<.84&&x.text.length>=2).slice(0,8);for(const x of targets)try{const c=await cropLine(file,x),d=await serverOCR([c,await enhance(c)]),v=single(d.rawText);if(v)map.set(x.id,v)}catch(e){console.warn('低置信复核失败',e)}return map}
async function enhance(url){const im=await new Promise((ok,no)=>{const i=new Image();i.onload=()=>ok(i);i.onerror=()=>no(Error('增强图片读取失败'));i.src=url}),s=Math.min(1.35,3600/im.naturalWidth),c=document.createElement('canvas');c.width=Math.round(im.naturalWidth*s);c.height=Math.round(im.naturalHeight*s);const x=c.getContext('2d',{alpha:false});x.fillStyle='#fff';x.fillRect(0,0,c.width,c.height);x.filter='grayscale(1) contrast(1.16) brightness(1.02)';x.drawImage(im,0,0,c.width,c.height);x.filter='none';return c.toDataURL('image/jpeg',.97)}
async function process(file){if(!file?.type?.startsWith('image/'))throw Error('请选择有效的运单图片');setStatus('正在启动本地中文OCR...',8);try{setStatus('正在检测整张运单版面...',18);const first=await predict(file),header=first.items.find(x=>/承运订单/.test(x.text));if(!header)throw Error('未检测到承运订单区域');setStatus('正在放大识别完整配送链...',34);let final=first.items,secondCount=0;try{const r=await deliveryCrop(file,first.items,header);if(r?.blob){const second=await predict(r.blob);secondCount=second.items.length;final=mergeSpatial(first.items,second.items.map(x=>abs(x,r)))}}catch(e){console.warn('配送链二次OCR失败',e)}final=final.map((x,i)=>({...x,id:i}));setStatus(`正在复核低置信文字...`,68);const review=await lowReview(file,final),text=final.map(x=>review.get(x.id)||x.text).filter(Boolean).join('\n');if(!text)throw Error('本地OCR没有形成有效文字');const input=$('manualOrderInput');if(input){input.value=text;input.dispatchEvent(new Event('input',{bubbles:true}));input.scrollTop=0}if($('charCount'))$('charCount').textContent=String(text.length);if($('statusCount'))$('statusCount').textContent=`PaddleOCR · 首次${first.items.length}区 · 配送链二次${secondCount}区 · 低置信复核${review.size}行 · 尚未解析门店`;setStatus('本地OCR完成，请核对原文。',100);if($('statusIcon'))$('statusIcon').textContent='✅';if(typeof window.homeToast==='function')window.homeToast('本地OCR完成，请核对原文后再开始解析');return{rawText:text,source:'paddleocr-v4'}}catch(e){console.warn('PaddleOCR失败，使用服务器视觉OCR兜底',e);setStatus('本地OCR暂不可用，启用视觉OCR兜底...',20);const im=await image(file),W=im.naturalWidth,H=im.naturalHeight,s=Math.min(1.8,3000/W),c=document.createElement('canvas');c.width=Math.round(W*s);c.height=Math.round(H*s);const x=c.getContext('2d',{alpha:false});x.drawImage(im,0,0,c.width,c.height);const u=c.toDataURL('image/jpeg',.96),d=await fetch('/api/ocr',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'same-origin',cache:'no-store',body:JSON.stringify({images:[u],route:route(),mode:'full'})}).then(r=>r.json());if(!d.success)throw Error(d.error||'视觉OCR失败');const text=norm(d.data?.rawText);const input=$('manualOrderInput');if(input){input.value=text;input.dispatchEvent(new Event('input',{bubbles:true}));input.scrollTop=0}if($('charCount'))$('charCount').textContent=String(text.length);setStatus('视觉OCR完成，请核对原文。',100);if($('statusIcon'))$('statusIcon').textContent='✅';return{rawText:text,source:'vlm-fallback'}}}
function setStatus(t,p){$('parseStatus')?.classList.add('active');if($('statusIcon'))$('statusIcon').textContent='⏳';if($('statusText'))$('statusText').textContent=t;if($('progressBar'))$('progressBar').style.width=`${p}%`}
window.callOCR=process;
})();
