/* 天友智配One - OCR：图片预处理与视觉文字提取。 */
(function(){
'use strict';
const $=id=>document.getElementById(id),MAX_SIDE=2200,TIMEOUT=35000;
let heicPromise=null,busy=false;
const route=()=>window.Auth?.getCurrentRoute?.()||'';
const norm=v=>String(v??'').replace(/\r\n/g,'\n').replace(/\r/g,'\n').replace(/[\u200B-\u200D\uFEFF]/g,'').trim();
function setStatus(text,progress=50,done=false){$('parseStatus')?.classList.add('active');if($('statusIcon'))$('statusIcon').textContent=done?'✅':'⏳';if($('statusText'))$('statusText').textContent=text;if($('progressBar'))$('progressBar').style.width=`${progress}%`}
function showError(text){if(typeof window.showError==='function')window.showError(text);else if(typeof window.homeToast==='function')window.homeToast(text,'warning');else alert(text)}
function placeholder(text){const s=norm(text).replace(/[“”\"'`]/g,'').replace(/\s+/g,'');if(!s)return true;return ['这里放整张图片的完整文字','这里放整张图片的完整原始文字','请提供您需要识别的图片','请上传您需要识别的图片','请上传需要识别的图片','请提供图片','请上传图片','图片无法读取','请重新上传图片'].some(v=>s===v||s.includes(v))}
async function loadHeic(){if(window.heic2any)return window.heic2any;if(heicPromise)return heicPromise;heicPromise=import('https://cdn.jsdelivr.net/npm/heic2any@0.0.4/+esm').then(m=>m.default||m).catch(e=>{heicPromise=null;throw e});return heicPromise}
async function normalizeFile(file){const n=String(file?.name||'').toLowerCase(),t=String(file?.type||'').toLowerCase();if(n.endsWith('.heic')||n.endsWith('.heif')||t==='image/heic'||t==='image/heif'){const fn=await loadHeic(),r=await fn({blob:file,type:'image/jpeg',quality:.94});return Array.isArray(r)?r[0]:r}return file}
async function bitmap(file){if(typeof createImageBitmap==='function'){try{return await createImageBitmap(file,{imageOrientation:'from-image'})}catch(_){}}const u=URL.createObjectURL(file);try{return await new Promise((res,rej)=>{const i=new Image();i.onload=()=>res(i);i.onerror=()=>rej(Error('图片读取失败'));i.src=u})}finally{URL.revokeObjectURL(u)}}
async function prepare(file){const src=await normalizeFile(file),img=await bitmap(src),ow=img.width||img.naturalWidth,oh=img.height||img.naturalHeight;if(!ow||!oh)throw Error('无法读取图片尺寸');const scale=Math.min(1,MAX_SIDE/Math.max(ow,oh)),w=Math.max(1,Math.round(ow*scale)),h=Math.max(1,Math.round(oh*scale)),c=document.createElement('canvas');c.width=w;c.height=h;const x=c.getContext('2d',{alpha:false});if(!x)throw Error('浏览器不支持图片处理');x.fillStyle='#fff';x.fillRect(0,0,w,h);x.imageSmoothingEnabled=true;x.imageSmoothingQuality='high';x.drawImage(img,0,0,w,h);img.close?.();const blob=await new Promise((res,rej)=>c.toBlob(b=>b?res(b):rej(Error('图片处理失败')),'image/jpeg',.9));return blob}
async function dataURL(blob){return await new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=()=>rej(Error('图片编码失败'));r.readAsDataURL(blob)})}
async function requestOCR(images){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),TIMEOUT);try{const response=await fetch('/api/ocr',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'same-origin',cache:'no-store',signal:controller.signal,body:JSON.stringify({images,route:route(),mode:'full'})}),data=await response.json().catch(()=>({}));if(!response.ok||!data.success)throw Error(data.error||`OCR请求失败（${response.status}）`);return norm(data.data?.rawText)}catch(e){if(e?.name==='AbortError')throw Error('运单识别等待超时，请重新上传图片重试');throw e}finally{clearTimeout(timer)}}
function putText(text){const input=$('manualOrderInput');if(!input)return false;input.value=text;input.removeAttribute('placeholder');input.dispatchEvent(new Event('input',{bubbles:true}));input.scrollTop=0;if($('charCount'))$('charCount').textContent=String(text.length);if($('statusCount'))$('statusCount').textContent='';return true}
async function process(file){if(busy)return;busy=true;try{if(!file?.type?.startsWith('image/')&&!/\.(heic|heif)$/i.test(file?.name||''))throw Error('请选择有效的运单图片');setStatus('正在准备运单图片...',8);const blob=await prepare(file);setStatus('正在提取运单数据，请稍等…',25);let text=await requestOCR([await dataURL(blob)]);if(!text||placeholder(text)||text.length<40){setStatus('正在提取运单数据，请稍等…',55);const enhanced=await new Promise((res,rej)=>{const img=new Image(),u=URL.createObjectURL(blob);img.onload=()=>{const c=document.createElement('canvas');c.width=img.naturalWidth;c.height=img.naturalHeight;const x=c.getContext('2d',{alpha:false});x.fillStyle='#fff';x.fillRect(0,0,c.width,c.height);x.filter='grayscale(1) contrast(1.12) brightness(1.03)';x.drawImage(img,0,0);x.filter='none';URL.revokeObjectURL(u);c.toBlob(b=>b?res(b):rej(Error('增强图片失败')),'image/jpeg',.92)};img.onerror=()=>{URL.revokeObjectURL(u);rej(Error('增强图片失败'))};img.src=u});text=await requestOCR([await dataURL(blob),await dataURL(enhanced)])}if(!text||placeholder(text))throw Error('OCR没有成功读取运单图片文字，请重新上传清晰、完整的运单图片');putText(text);setStatus('正在提取运单数据，请稍等…',100,true);window.homeToast?.('运单文字提取完成，请核对原文后再开始解析');return{rawText:text,source:'server-vision'}}catch(e){console.error('OCR:',e);showError(e?.message||'运单图片处理失败');throw e}finally{busy=false}}
window.callOCR=process;
window.triggerUpload=function(type){if(busy)return;const input=document.createElement('input');input.type='file';input.accept='image/*,.heic,.heif';if(type==='camera')input.capture='environment';input.style.display='none';input.onchange=()=>{const f=input.files?.[0];if(f)process(f).catch(()=>{})};document.body.appendChild(input);input.click();setTimeout(()=>input.remove(),1500)};
window.triggerCameraUpload=()=>window.triggerUpload('camera');
})();
