/* 天友智配One - OCR V4
 * 第一阶段：图片 -> 可核对的高保真运单原文。
 * 主识别：PaddleOCR PP-OCRv5；长运单先定位“承运订单”，再对该区域进行二次高分辨率识别。
 * 低置信文字才送服务器视觉模型复核；服务器视觉OCR仅作最终兜底。
 * 第一阶段绝不使用线路库、业务字典或硬编码答案纠错。
 */
(function(){
'use strict';
const $=id=>document.getElementById(id);
const SDK='https://cdn.jsdelivr.net/npm/@paddleocr/paddleocr-js@0.4.2/+esm';
const LOW_SCORE=.84,MAX_VLM_REVIEW=8;
let paddlePromise=null,paddleOCR=null;
const route=()=>window.Auth?.getCurrentRoute?.()||'';
const norm=v=>String(v??'').replace(/\r\n/g,'\n').replace(/\r/g,'\n').replace(/[\u200B-\u200D\uFEFF]/g,'').trim();
const line=v=>String(v??'').replace(/[→＞》➜➤⇒]/g,'->').replace(/-\s*>/g,'->').replace(/[“”‘’]/g,'').replace(/[ \t]+/g,' ').trim();
const minX=p=>p?.length?Math.min(...p.map(v=>+v?.[0]||0)):0;
const minY=p=>p?.length?Math.min(...p.map(v=>+v?.[1]||0)):0;
const maxX=p=>p?.length?Math.max(...p.map(v=>+v?.[0]||0)):0;
const maxY=p=>p?.length?Math.max(...p.map(v=>+v?.[1]||0)):0;
const boxH=p=>Math.max(1,maxY(p)-minY(p));
const centerY=x=>(minY(x.poly)+maxY(x.poly))/2;
function readingOrder(a,b){const d=Math.abs(centerY(a)-centerY(b)),t=Math.max(boxH(a.poly),boxH(b.poly))*.62;return d<=t?minX(a.poly)-minX(b.poly):centerY(a)-centerY(b)}
function setStatus(t,p=50){$('parseStatus')?.classList.add('active');if($('statusIcon'))$('statusIcon').textContent='⏳';if($('statusText'))$('statusText').textContent=t;if($('progressBar'))$('progressBar').style.width=`${p}%`}
function showError(t){if(typeof window.showError==='function')window.showError(t);else if(typeof window.homeToast==='function')window.homeToast(t,'warning');else alert(t)}
function placeholder(v){const s=norm(v).replace(/[“”\"'`]/g,'').replace(/\s+/g,'');return !s||['这里放整张图片的完整文字','这里放整张图片的完整原始文字','请提供您需要识别的图片','请上传您需要识别的图片','请上传需要识别的图片','请提供图片','请上传图片','图片无法读取','请重新上传图片'].some(x=>s===x||s.includes(x))}
async function getOCR(){if(paddleOCR)return paddleOCR;if(paddlePromise)return paddlePromise;paddlePromise=(async()=>{const m=await import(SDK),C=m.PaddleOCR||m.default?.PaddleOCR||m.default;if(!C?.create)throw Error('PaddleOCR加载失败');paddleOCR=await C.create({lang:'ch',ocrVersion:'PP-OCRv5',worker:true,textDetectionBatchSize:2,textRecognitionBatchSize:6,ortOptions:{backend:'wasm',numThreads:window.crossOriginIsolated?2:1,simd:true}});return paddleOCR})().catch(e=>{paddlePromise=null;throw e});return paddlePromise}
async function predict(input){const r=(await getOCR()).predict(input,{textRecScoreThresh:0})?.[0];if(!r?.items?.length)throw Error('PaddleOCR未检测到文字');return{items:r.items.map((x,i)=>({id:i,text:line(x.text),score:Number(x.score),poly:Array.isArray(x.poly)?x.poly:[]})).filter(x=>x.text).sort(readingOrder),metrics:r.metrics||{}}}
async function loadImage(file){const u=URL.createObjectURL(file);try{return await new Promise((ok,no)=>{const i=new Image();i.onload=()=>ok(i);i.onerror=()=>no(Error('图片读取失败'));i.src=u})}finally{URL.revokeObjectURL(u)}}
async function cropDelivery(file,items,header){const im=await loadImage(file),W=im.naturalWidth,H=im.naturalHeight,r=items.filter(x=>x.poly.length&&minY(x.poly)>=minY(header.poly));if(!r.length)return null;const top=Math.max(0,minY(header.poly)-boxH(header.poly)*2),left=Math.max(0,Math.min(...r.map(x=>minX(x.poly)))-Math.max(24,W*.012)),right=Math.min(W,Math.max(...r.map(x=>maxX(x.poly)))+Math.max(24,W*.012)),w=Math.max(1,right-left),scale=Math.max(1,Math.min(2.8,Math.max(1800,w*1.8)/w)),c=document.createElement('canvas');c.width=Math.round(w*scale);c.height=Math.round((H-top)*scale);const ctx=c.getContext('2d',{alpha:false});ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';ctx.fillStyle='#fff';ctx.fillRect(0,0,c.width,c.height);ctx.drawImage(im,left,top,w,H-top,0,0,c.width,c.height);return{blob:await new Promise(ok=>c.toBlob(ok,'image/jpeg',.97)),left,top,scale}}
function absolute(x,r){return{...x,poly:x.poly.map(p=>[(+p[0]/r.scale)+r.left,(+p[1]/r.scale)+r.top])}}
function overlap(a,b){if(!a.poly.length||!b.poly.length)return 0;const ax0=minX(a.poly),ax1=maxX(a.poly),ay0=minY(a.poly),ay1=maxY(a.poly),bx0=minX(b.poly),bx1=maxX(b.poly),by0=minY(b.poly),by1=maxY(b.poly),ox=Math.max(0,Math.min(ax1,bx1)-Math.max(ax0,bx0)),oy=Math.max(0,Math.min(ay1,by1)-Math.max(ay0,by0));return ox*oy/Math.max(1,Math.min((ax1-ax0)*(ay1-ay0),(bx1-bx0)*(by1-by0)))}
function mergeSpatial(a,b){const out=[],used=new Set();for(const x of a){let hit=-1,best=0;for(let i=0;i<b.length;i++){if(used.has(i))continue;const q=overlap(x,b[i]);if(q>.35&&q>best){best=q;hit=i}}if(hit>=0){const y=b[hit];used.add(hit);out.push({...x,text:y.text.length>x.text.length?y.text:x.text,score:Math.max(x.score||0,y.score||0)})}else out.push(x)}b.forEach((x,i)=>{if(!used.has(i))out.push(x)});return out.sort(readingOrder).map((x,i)=>({...x,id:i}))}
async function cropLine(file,item){const im=await loadImage(file),xs=item.poly.map(p=>+p[0]||0),ys=item.poly.map(p=>+p[1]||0),px=Math.max(22,(Math.max(...xs)-Math.min(...xs))*.06),py=Math.max(18,(Math.max(...ys)-Math.min(...ys))*.65),l=Math.max(0,Math.floor(Math.min(...xs)-px)),t=Math.max(0,Math.floor(Math.min(...ys)-py)),r=Math.min(im.naturalWidth,Math.ceil(Math.max(...xs)+px)),b=Math.min(im.naturalHeight,Math.ceil(Math.max(...ys)+py)),w=Math.max(1,r-l),hh=Math.max(1,b-t),s=Math.min(3,Math.max(2,1800/w)),c=document.createElement('canvas');c.width=Math.round(w*s);c.height=Math.round(hh*s);const ctx=c.getContext('2d',{alpha:false});ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';ctx.fillStyle='#fff';ctx.fillRect(0,0,c.width,c.height);ctx.filter='grayscale(1) contrast(1.12) brightness(1.02)';ctx.drawImage(im,l,t,w,hh,0,0,c.width,c.height);ctx.filter='none';return c.toDataURL('image/jpeg',.97)}
async function enhance(url){const im=await new Promise((ok,no)=>{const i=new Image();i.onload=()=>ok(i);i.onerror=()=>no(Error('增强图片读取失败'));i.src=url}),s=Math.min(1.35,3600/im.naturalWidth),c=document.createElement('canvas');c.width=Math.round(im.naturalWidth*s);c.height=Math.round(im.naturalHeight*s);const x=c.getContext('2d',{alpha:false});x.fillStyle='#fff';x.fillRect(0,0,c.width,c.height);x.filter='grayscale(1) contrast(1.16) brightness(1.02)';x.drawImage(im,0,0,c.width,c.height);x.filter='none';return c.toDataURL('image/jpeg',.97)}
async function serverLineOCR(images){const r=await fetch('/api/ocr',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'same-origin',cache:'no-store',body:JSON.stringify({images,route:route(),mode:'line'})}),d=await r.json().catch(()=>({}));if(!r.ok||!d.success)throw Error(d.error||`OCR请求失败(${r.status})`);return d.data||{}}
async function reviewLowConfidence(file,items){const map=new Map();for(const x of items.filter(v=>Number.isFinite(v.score)&&v.score<LOW_SCORE&&v.text.length>=2).slice(0,MAX_VLM_REVIEW))try{const c=await cropLine(file,x),d=await serverLineOCR([c,await enhance(c)]),v=norm(d.rawText).split('\n').map(line).filter(t=>t&&/[\u4e00-\u9fffA-Za-z0-9]/.test(t)).sort((a,b)=>b.length-a.length)[0];if(v)map.set(x.id,v)}catch(e){console.warn('低置信行复核失败',e)}return map}
async function fullFallback(file){const im=await loadImage(file),W=im.naturalWidth,H=im.naturalHeight,s=Math.min(1.8,3000/W),c=document.createElement('canvas');c.width=Math.round(W*s);c.height=Math.round(H*s);const x=c.getContext('2d',{alpha:false});x.drawImage(im,0,0,c.width,c.height);const r=await fetch('/api/ocr',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'same-origin',cache:'no-store',body:JSON.stringify({images:[c.toDataURL('image/jpeg',.96)],route:route(),mode:'full'})}),d=await r.json().catch(()=>({}));if(!r.ok||!d.success)throw Error(d.error||'视觉OCR失败');return norm(d.data?.rawText)}
async function process(file){if(!file?.type?.startsWith('image/'))throw Error('请选择有效的运单图片');setStatus('正在启动本地中文OCR...',8);try{setStatus('正在检测整张运单版面...',18);const first=await predict(file),header=first.items.find(x=>/承运订单/.test(x.text));if(!header)throw Error('未检测到承运订单区域');setStatus('正在放大识别完整配送链...',35);let final=first.items,secondCount=0;try{const region=await cropDelivery(file,first.items,header);if(region?.blob){const second=await predict(region.blob);secondCount=second.items.length;final=mergeSpatial(first.items,second.items.map(x=>absolute(x,region)))}}catch(e){console.warn('配送链区域二次OCR失败',e)}final=final.map((x,i)=>({...x,id:i}));setStatus('正在复核低置信文字...',70);const review=await reviewLowConfidence(file,final),text=final.map(x=>review.get(x.id)||x.text).filter(Boolean).join('\n');if(!text||placeholder(text))throw Error('本地OCR没有形成有效文字');const input=$('manualOrderInput');if(input){input.value=text;input.dispatchEvent(new Event('input',{bubbles:true}));input.scrollTop=0}if($('charCount'))$('charCount').textContent=String(text.length);if($('statusCount'))$('statusCount').textContent=`PaddleOCR · 首次${first.items.length}区 · 配送链二次${secondCount}区 · 低置信复核${review.size}行 · 尚未解析门店`;setStatus('本地OCR完成，请核对原文。',100);if($('statusIcon'))$('statusIcon').textContent='✅';if(typeof window.homeToast==='function')window.homeToast('本地OCR完成，请核对原文后再开始解析');return{rawText:text,source:'paddleocr-v4'}}catch(localError){console.warn('PaddleOCR失败，启用服务器视觉OCR兜底',localError);setStatus('本地OCR暂不可用，启用视觉OCR兜底...',20);const text=await fullFallback(file);if(!text||placeholder(text))throw Error('OCR没有成功读取运单图片文字，请重新上传清晰、完整的运单图片');const input=$('manualOrderInput');if(input){input.value=text;input.dispatchEvent(new Event('input',{bubbles:true}));input.scrollTop=0}if($('charCount'))$('charCount').textContent=String(text.length);setStatus('视觉OCR完成，请核对原文。',100);if($('statusIcon'))$('statusIcon').textContent='✅';return{rawText:text,source:'vlm-fallback'}}}
window.callOCR=process;
window.triggerUpload=function(){const i=document.createElement('input');i.type='file';i.accept='image/*';i.style.display='none';i.onchange=()=>{const f=i.files?.[0];if(f)process(f).catch(e=>{console.error(e);showError(e?.message||'运单图片处理失败')})};document.body.appendChild(i);i.click();setTimeout(()=>i.remove(),1000)};
window.triggerCameraUpload=function(){const i=document.createElement('input');i.type='file';i.accept='image/*';i.capture='environment';i.style.display='none';i.onchange=()=>{const f=i.files?.[0];if(f)process(f).catch(e=>{console.error(e);showError(e?.message||'运单图片处理失败')})};document.body.appendChild(i);i.click();setTimeout(()=>i.remove(),1000)};
})();
