/* 天友智配One - 当日订单人工确认与录入 */
(function(){
  'use strict';
  let reviewState=[];
  let parsedState=[];
  let metaState={};
  const $=id=>document.getElementById(id);
  const toast=(msg,type='')=>window.homeToast?.(msg,type);
  const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const routeContext=()=>typeof Auth!=='undefined'&&Auth.getCurrentRoute?Auth.getCurrentRoute():'';
  function ensurePanel(){if($('reviewPanel'))return $('reviewPanel');const panel=document.createElement('div');panel.id='reviewPanel';panel.style.cssText='display:none;margin:12px 0;padding:14px;background:rgba(255,176,32,.08);border:1px solid rgba(255,176,32,.25);border-radius:16px;color:#fff';panel.innerHTML='<div style="font-weight:700;font-size:15px;margin-bottom:6px">⚠ 待确认门店</div><div id="reviewHint" style="font-size:11px;color:#AAB6C2;margin-bottom:10px"></div><div id="reviewList"></div>';const status=$('parseStatus');if(status?.parentNode)status.parentNode.insertBefore(panel,status.nextSibling);else document.querySelector('.upload-sheet')?.prepend(panel);return panel;}
  function candidateList(item){const values=[item?.candidate,...(Array.isArray(item?.candidates)?item.candidates:[])].map(v=>String(v||'').trim()).filter(Boolean);return [...new Set(values)];}
  function renderReview(items){reviewState=(Array.isArray(items)?items:[]).filter(item=>item?.needsReview);const panel=ensurePanel();const list=$('reviewList');if(!reviewState.length){panel.style.display='none';if(list)list.innerHTML='';return;}panel.style.display='block';if($('reviewHint'))$('reviewHint').textContent=`发现 ${reviewState.length} 家疑似门店，请确认后再录入。选择正确候选后，系统会记住这次对应关系。`;if(!list)return;list.innerHTML='';reviewState.forEach((item,index)=>{const row=document.createElement('div');row.style.cssText='padding:10px 0;border-top:1px solid rgba(255,255,255,.08)';row.innerHTML=`<div style="font-size:13px;margin-bottom:6px"><span style="color:#FFB020">${esc(item.code||`R${String(index+1).padStart(2,'0')}`)}</span>　识别：<b>${esc(item.name)}</b></div><div style="font-size:10px;color:#718092;margin-bottom:7px">匹配度 ${Math.round(Number(item.matchScore||0)*100)}%</div>`;const select=document.createElement('select');select.style.cssText='width:100%;height:40px;border-radius:10px;background:#10161D;color:#fff;border:1px solid rgba(255,255,255,.1);padding:0 10px;font-size:12px';const candidates=candidateList(item);select.innerHTML='<option value="">请选择处理方式</option>'+candidates.map((name,i)=>`<option value="candidate:${i}">采用候选：${esc(name)}</option>`).join('')+'<option value="new">作为新增门店</option>';select.value=item._choice||'';select.onchange=()=>{item._choice=select.value;item._selectedCandidate=select.value.startsWith('candidate:')?candidates[Number(select.value.slice(10))]||'':'';};row.appendChild(select);list.appendChild(row);});const button=document.createElement('button');button.type='button';button.textContent='✓ 应用确认';button.style.cssText='width:100%;height:40px;margin-top:10px;border:0;border-radius:11px;background:#2457A6;color:#fff;font-weight:600';button.onclick=applyReview;list.appendChild(button);}
  async function applyReview(){let pending=0;for(const item of reviewState)if(!item._choice)pending++;if(pending){toast(`还有 ${pending} 家门店未确认`,'warning');return;}const button=document.querySelector('#reviewList button');if(button){button.disabled=true;button.textContent='正在应用…';}try{for(const item of reviewState){const target=parsedState.find(store=>store===item||store.code===item.code||store.name===item.name);if(!target)continue;if(item._choice==='new'){target.needsReview=false;target.candidate='';target.candidates=[];target.matchType='new';target.matched=false;target.isNew=true;target.matchScore=0;}else{const selected=String(item._selectedCandidate||'').trim();if(!selected)throw Error('请选择正确的候选门店');const rawName=String(item.name||'').trim();const rawNames=Array.isArray(target.rawNames)?target.rawNames.filter(Boolean):[];if(rawName&&!rawNames.includes(rawName))rawNames.push(rawName);target.rawNames=rawNames.slice(-5);target.baseName=selected;target.baseCode=item.candidateCode||'';target.name=selected;target.needsReview=false;target.candidate='';target.candidates=[];target.matchType='confirmed';target.matched=true;target.isNew=false;target.matchScore=1;}}renderReview([]);writeReviewText(parsedState);toast('待确认门店已处理，确认关系将在本次订单确认后保存到当前线路云端学习库');}catch(error){toast(error.message||'处理失败，请重试','warning');}finally{if(button){button.disabled=false;button.textContent='✓ 应用确认';}}}
  function writeReviewText(stores){const input=$('manualOrderInput');if(!input)return;const lines=['【当日订单信息】',`日期：${metaState.date||'未识别'}`,`线路：${metaState.route||routeContext()||'未识别'}`,`车辆：${metaState.vehicle||'未识别'}`,`门店数：${stores.length}家`,`总重量：${metaState.totalWeight||'未识别'}`,'','【门店列表】'];stores.forEach((store,index)=>{const mark=store?.isNew?'⚠️ 新增：':store?.needsReview?'⚠️ 待确认：':'';lines.push(`${String(index+1).padStart(2,'0')}. ${mark}${String(store?.name||'').trim()}`);});input.value=lines.join('\n');}
  function syncParsed(data){const d=data||{};parsedState=Array.isArray(d.stores)?d.stores.map(item=>({...item})):[];metaState={route:d.route||routeContext()||'',date:d.date||'',vehicle:d.vehicle||'',totalWeight:normalizeWeight(d.totalWeight),rawOrderCount:Number(d.rawOrderCount)||0,recognizedCount:Number(d.recognizedCount)||parsedState.length,source:d.source||'web-confirm'};renderReview(parsedState);}
  function normalizeWeight(value){if(value===null||value===undefined||value==='')return '';const text=String(value).trim().replace(/,/g,'');const match=text.match(/[\d]+(?:\.\d+)?/);if(!match)return '';const n=Number(match[0]);if(!Number.isFinite(n)||n<=0)return n===0?'0.0t':'';const hasKg=/kg|千克|公斤/i.test(text);const hasTon=/吨|\bt\b/i.test(text);const tons=hasTon?n:hasKg?n/1000:n>=1000?n/1000:n;return `${(Math.round((tons+Number.EPSILON)*10)/10).toFixed(1)}t`;}
  function weightFromText(text){const source=String(text||'').replace(/\s+/g,' ');const match=source.match(/总\s*重\s*量\s*[:：]?\s*([\d]+(?:\.[\d]+)?)\s*(kg|千克|公斤|吨|t)?/i)||source.match(/(?:总重|重量)\s*[:：]?\s*([\d]+(?:\.[\d]+)?)\s*(kg|千克|公斤|吨|t)?/i);return match?normalizeWeight(`${match[1]}${match[2]||''}`):'';}
  window.onOrderParsed=syncParsed;
  async function reparseEditedText(){const text=String($('manualOrderInput')?.value||'').trim();if(!text)throw Error('请先输入或识别运单文字');const route=routeContext();if(!route)throw Error('未指定配送线路');const response=await fetch('/api/parse',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'same-origin',cache:'no-store',body:JSON.stringify({text,route})});const data=await response.json().catch(()=>({}));if(!response.ok||!data.success)throw Error(data.error||`重新解析失败（${response.status}）`);syncParsed(data.data||{});return data.data||{};}
  async function saveConfirmedLearning(){const route=routeContext();if(!route)return;const items=[];for(const item of parsedState){if(!item||item.isNew===true||item.matched!==true||item.needsReview===true)continue;const baseName=String(item.baseName||item.name||'').trim();const rawNames=Array.isArray(item.rawNames)?item.rawNames.map(v=>String(v||'').trim()).filter(Boolean):[];const fallback=String(item.rawName||'').trim();if(fallback&&!rawNames.includes(fallback))rawNames.push(fallback);for(const rawName of rawNames){if(!rawName||rawName===baseName)continue;items.push({rawName,baseName,baseCode:String(item.baseCode||'').trim()});}}if(!items.length)return;const unique=new Map();for(const item of items){const key=`${item.rawName}\u0000${item.baseCode}\u0000${item.baseName}`;unique.set(key,item);}try{const response=await fetch('/api/store-learning',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'same-origin',cache:'no-store',body:JSON.stringify({items:[...unique.values()]})});const data=await response.json().catch(()=>({}));if(!response.ok||!data.success)console.warn('门店学习库保存失败',data.error||response.status);}catch(error){console.warn('门店学习库请求失败',error);}}
  async function confirm(){const input=$('manualOrderInput');if(!parsedState.length){if(!String(input?.value||'').trim()){toast('请先点击“开始解析”','warning');return;}try{toast('正在应用人工修改...');await reparseEditedText();}catch(error){toast(error.message||'人工修改重新解析失败','warning');return;}}const pending=parsedState.filter(item=>item?.needsReview);if(pending.length){renderReview(pending);toast(`请先确认 ${pending.length} 家疑似门店`,'warning');return;}const route=routeContext();if(!route){toast('未指定配送线路','warning');return;}const button=$('confirmBtn');if(button){button.disabled=true;button.textContent='正在确认…';}const currentText=String(input?.value||'');const totalWeight=metaState.totalWeight||weightFromText(currentText);const date=metaState.date||'';try{const response=await fetch('/api/confirm',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'same-origin',cache:'no-store',body:JSON.stringify({orders:parsedState,route,date,vehicle:metaState.vehicle||'',totalWeight,rawText:currentText,source:metaState.source||'web-confirm',recognizedCount:Number(metaState.recognizedCount)||parsedState.length,rawOrderCount:Number(metaState.rawOrderCount)||0})});const data=await response.json().catch(()=>({}));if(!response.ok||!data.success){if(data.code==='REVIEW_REQUIRED')renderReview(data.review||[]);throw Error(data.error||`确认失败（${response.status}）`);}await saveConfirmedLearning();const savedDate=data.data?.date||date;const savedBatch=data.data?.orderBatchId||'';toast(`已确认并录入 ${data.data?.count||parsedState.length} 家门店`);$('uploadOverlay')?.classList.remove('active');const params=new URLSearchParams({route});if(savedDate)params.set('date',savedDate);if(savedBatch)params.set('orderBatchId',savedBatch);location.href=`pages/order_detail.html?${params.toString()}`;}catch(error){toast(error.message||'确认入库失败','warning');}finally{if(button){button.disabled=false;button.textContent='确认录入';}}}
  window.submitManualOrder=confirm;
  window.renderReviewStores=renderReview;
  ensurePanel();
})();
