/* 天友智配One - 解析结果人工确认层 */
(function(){
  'use strict';
  let reviewState=[], parsedState=[], metaState={};
  const $=id=>document.getElementById(id);
  function toast(msg,type=''){let el=$('homeToast');if(!el){el=document.createElement('div');el.id='homeToast';el.className='toast';document.body.appendChild(el)}el.textContent=msg;el.className=`toast show ${type}`;clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2800)}
  function ensurePanel(){if($('reviewPanel'))return $('reviewPanel');const p=document.createElement('div');p.id='reviewPanel';p.style.cssText='display:none;margin:12px 0;padding:14px;background:rgba(255,176,32,.08);border:1px solid rgba(255,176,32,.25);border-radius:16px;color:#fff';p.innerHTML='<div style="font-weight:700;font-size:15px;margin-bottom:6px">⚠ 待确认门店</div><div id="reviewHint" style="font-size:11px;color:#AAB6C2;margin-bottom:10px"></div><div id="reviewList"></div>';const s=$('parseStatus');if(s?.parentNode)s.parentNode.insertBefore(p,s.nextSibling);else document.querySelector('.upload-sheet')?.prepend(p);return p}
  function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  function render(items){reviewState=(Array.isArray(items)?items:[]).filter(x=>x?.needsReview);const p=ensurePanel(),list=$('reviewList');if(!reviewState.length){p.style.display='none';if(list)list.innerHTML='';return}p.style.display='block';if($('reviewHint'))$('reviewHint').textContent=`发现 ${reviewState.length} 家疑似门店。确认后才能录入正式订单。`;list.innerHTML='';reviewState.forEach((x,i)=>{const row=document.createElement('div');row.style.cssText='padding:10px 0;border-top:1px solid rgba(255,255,255,.08)';row.innerHTML=`<div style="font-size:13px;margin-bottom:6px"><span style="color:#FFB020">${esc(x.code||`R${String(i+1).padStart(2,'0')}`)}</span>　识别：<b>${esc(x.name)}</b></div><div style="font-size:10px;color:#718092;margin-bottom:7px">匹配度 ${Math.round(Number(x.matchScore||0)*100)}%</div>`;const sel=document.createElement('select');sel.style.cssText='width:100%;height:40px;border-radius:10px;background:#10161D;color:#fff;border:1px solid rgba(255,255,255,.1);padding:0 10px;font-size:12px';sel.innerHTML=`<option value="">请选择处理方式</option><option value="candidate">采用候选：${esc(x.candidate||'')}</option><option value="new">作为新增门店</option>`;sel.onchange=()=>x._choice=sel.value;row.appendChild(sel);list.appendChild(row)});const b=document.createElement('button');b.type='button';b.textContent='✓ 应用确认';b.style.cssText='width:100%;height:40px;margin-top:10px;border:0;border-radius:11px;background:#2457A6;color:#fff;font-weight:600';b.onclick=apply;list.appendChild(b)}
  function apply(){let n=0;reviewState.forEach(x=>{const c=x._choice;if(!c){n++;return}const t=parsedState.find(y=>y===x||y.code===x.code||y.name===x.name);if(!t)return;if(c==='new'){t.needsReview=false;t.candidate='';t.matchType='new';t.matched=false;t.isNew=true;t.matchScore=0}else{t.name=x.candidate;t.needsReview=false;t.candidate='';t.matchType='confirmed';t.matched=true;t.isNew=false;t.matchScore=1}});if(n){toast(`还有 ${n} 家门店未确认`,'warning');return}render([]);toast('待确认门店已处理，请点击“确认录入”')}
  async function confirm(){if(!parsedState.length){toast('请先点击“开始解析”','warning');return}const pending=parsedState.filter(x=>x?.needsReview);if(pending.length){render(pending);toast(`请先确认 ${pending.length} 家疑似门店`,'warning');return}const route=typeof Auth!=='undefined'?Auth.getCurrentRoute():'';if(!route){toast('未指定配送线路','warning');return}const btn=$('confirmBtn');if(btn){btn.disabled=true;btn.textContent='正在确认…'}try{const r=await fetch('/api/confirm',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'same-origin',cache:'no-store',body:JSON.stringify({orders:parsedState,route,date:metaState.date||'',vehicle:metaState.vehicle||'',totalWeight:metaState.totalWeight||'',source:metaState.source||'web-confirm',recognizedCount:Number(metaState.recognizedCount)||parsedState.length,rawOrderCount:Number(metaState.rawOrderCount)||0})});const d=await r.json().catch(()=>({}));if(!r.ok||!d.success){if(d.code==='REVIEW_REQUIRED')render(d.review||[]);throw Error(d.error||`确认失败（${r.status}）`)}toast(`已确认并录入 ${d.data?.count||parsedState.length} 家门店`);$('uploadOverlay')?.classList.remove('active');setTimeout(()=>{location.href=`pages/order_detail.html?route=${encodeURIComponent(route)}`},400)}catch(e){toast(e.message||'确认入库失败','warning')}finally{if(btn){btn.disabled=false;btn.textContent='确认录入'}}}
  const nativeFetch=window.fetch.bind(window);window.fetch=async function(){const response=await nativeFetch(...arguments);try{const url=typeof arguments[0]==='string'?arguments[0]:arguments[0]?.url||'';if(url.includes('/api/parse')&&response.ok){const clone=response.clone();const d=await clone.json();if(d?.success){parsedState=Array.isArray(d.data?.stores)?d.data.stores.map(x=>({...x})):[];metaState={date:d.data?.date||'',vehicle:d.data?.vehicle||'',totalWeight:d.data?.totalWeight||'',rawOrderCount:d.data?.rawOrderCount||0,recognizedCount:d.data?.recognizedCount||parsedState.length,source:'web-confirm'};setTimeout(()=>render(parsedState.filter(x=>x?.needsReview)),0)}}}catch(_){ }return response};
  window.submitManualOrder=confirm;window.renderReviewStores=render;ensurePanel();
})();
