/* 天友智配One - 首页业务逻辑
 * 第一阶段：图片 -> OCR -> 完整原始文字输入框
 * OCR阶段不解析门店、不比对基准、不排序、不保存订单。
 */
(function(){
  'use strict';
  let baseStores=[],parsedOrders=[],serverToday=null,pendingMeta={};
  const $=id=>document.getElementById(id);
  function toast(message,type=''){let el=$('homeToast');if(!el){el=document.createElement('div');el.id='homeToast';el.className='toast';document.body.appendChild(el)}el.textContent=message;el.className=`toast show ${type}`;clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),2800)}
  function error(message){const box=$('error-box');if(!box)return;box.textContent='页面错误：'+message;box.classList.add('show');setTimeout(()=>box.classList.remove('show'),5000)}
  function today(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
  function storeName(store){return String(store?.name||store?.storeName||store?.shopName||'').trim()}
  function currentRoute(){const sessionRoute=Auth.getCurrentRoute();if(sessionRoute!=='admin')return sessionRoute;return String(new URLSearchParams(location.search).get('route')||'').trim()}
  async function loadBaseStores(){const route=currentRoute();if(!route)throw Error(Auth.getCurrentRoute()==='admin'?'管理员查看配送数据时必须指定线路':'未绑定线路');const response=await fetch(`/api/routes?route=${encodeURIComponent(route)}`,{cache:'no-store',credentials:'same-origin'});if(!response.ok)throw Error(response.status===401?'登录已失效，请重新登录':`线路基准读取失败（${response.status}）`);const data=await response.json();const stores=Array.isArray(data)?data:(data?.stores||data?.data||[]);if(!Array.isArray(stores)||!stores.length)throw Error('当前线路暂无基准门店数据');baseStores=stores;return baseStores}
  async function loadServerToday(date=''){const route=currentRoute();if(!route)throw Error('未指定配送线路');const params=new URLSearchParams({route});if(date)params.set('date',date);const response=await fetch(`/api/orders?${params}`,{cache:'no-store',credentials:'same-origin'});if(!response.ok)throw Error(response.status===401?'登录已失效，请重新登录':`今日订单读取失败（${response.status}）`);const data=await response.json();serverToday=data?.today||null;return serverToday}
  function parseWeight(value){if(value===null||value===undefined||value==='')return 0;const text=String(value).trim().replace(/,/g,'');const match=text.match(/[\d]+(?:\.\d+)?/);if(!match)return 0;const n=Number(match[0]);return Number.isFinite(n)?(/吨|\bt\b/i.test(text)?n*1000:n):0}
  function updateSummary(){const orders=Array.isArray(serverToday?.orders)?serverToday.orders:[],count=orders.length,weight=parseWeight(serverToday?.totalWeight),route=serverToday?.route||currentRoute()||'',vehicle=serverToday?.vehicle||'';if($('menuRoute'))$('menuRoute').textContent=route||'未选择线路';if($('homeRoute'))$('homeRoute').textContent=vehicle?`🚚 ${vehicle}`:`🚚 ${route}`;if($('storeCount'))$('storeCount').textContent=count?`${count}家门店`:'暂无今日订单';if($('totalWeight'))$('totalWeight').textContent=weight?`${Number(weight.toFixed(2))} kg`:'暂无数据';if($('statusDot'))$('statusDot').style.background=count?'#27AE60':'#5A6A7A'}
  function renderStatus(status,count=0,message=''){const box=$('parseStatus');if(!box)return;box.classList.add('active');if($('statusIcon'))$('statusIcon').textContent=status==='success'?'✅':status==='error'?'⚠️':'⏳';if($('statusText'))$('statusText').textContent=message||(status==='success'?'处理完成':status==='error'?'处理失败':'正在处理...');if($('progressBar'))$('progressBar').style.width=status==='success'||status==='error'?'100%':'50%';if($('statusCount'))$('statusCount').textContent=count?`解析得到 ${count} 家门店`:''}
  function renderTags(items){const box=$('parsedTags');if(!box)return;box.innerHTML='';items.slice(0,80).forEach((item,i)=>{const tag=document.createElement('span');tag.textContent=`${String(item.code||item.displayCode||i+1).padStart(2,'0')} ${item.isNew?'⚠️ ':''}${item.name}`;tag.style.cssText='background:rgba(36,87,166,.18);padding:4px 7px;border-radius:7px;color:#AFC7E8;font-size:10px;';box.appendChild(tag)})}
  function setOCRText(text){const input=$('manualOrderInput');if(input){input.value=String(text??'');input.dispatchEvent(new Event('input',{bubbles:true}));input.scrollTop=0}}
  function extractLocalMeta(text){const s=String(text||''),d=s.match(/(20\d{2}[-/.年]\d{1,2}[-/.月]\d{1,2}日?)/),v=s.match(/(?:车牌号|车牌|车辆)\s*[:：]?\s*([\u4e00-\u9fa5][A-Z0-9]{5,7})/i),w=s.match(/总重量\s*[:：]?\s*([\d]+(?:\.\d+)?)\s*(kg|KG|千克|公斤|吨|t)?/i),c=s.match(/总数量\s*[:：]?\s*(\d+)/);return{date:d?d[1]:'',vehicle:v?v[1]:'',totalWeight:w?`${w[1]}${w[2]||'kg'}`:'',rawOrderCount:c?Number(c[1]):0}}
  async function parseOrderText(text){const route=currentRoute();if(!route)throw Error('未指定配送线路');const response=await fetch('/api/parse',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text,route}),credentials:'same-origin',cache:'no-store'});const data=await response.json().catch(()=>({}));if(!response.ok||!data.success)throw Error(data.error||`解析接口错误（${response.status}）`);return data.data}

  // 将手机相机的大图压缩到适合在线OCR的尺寸，同时保持文字清晰。
  // 不修改OCR文字内容；这里只降低上传体积，避免移动端请求过大导致OCR失败。
  async function imageToDataURL(file){
    if(!file||!file.type.startsWith('image/'))throw Error('请选择有效的运单图片');
    const sourceURL=URL.createObjectURL(file);
    try{
      const image=await new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=()=>reject(Error('图片读取失败'));img.src=sourceURL});
      const maxSide=2400;
      const scale=Math.min(1,maxSide/Math.max(image.naturalWidth||image.width,image.naturalHeight||image.height));
      const canvas=document.createElement('canvas');
      canvas.width=Math.max(1,Math.round((image.naturalWidth||image.width)*scale));
      canvas.height=Math.max(1,Math.round((image.naturalHeight||image.height)*scale));
      const ctx=canvas.getContext('2d',{alpha:false});
      if(!ctx)throw Error('无法准备图片处理环境');
      ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);
      ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';
      ctx.drawImage(image,0,0,canvas.width,canvas.height);
      return canvas.toDataURL('image/jpeg',0.92);
    }finally{URL.revokeObjectURL(sourceURL)}
  }

  async function callOCR(file){const image=await imageToDataURL(file),response=await fetch('/api/ocr',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({image,route:currentRoute()}),credentials:'same-origin',cache:'no-store'}),data=await response.json().catch(()=>({}));if(!response.ok||!data.success)throw Error(data.error||`OCR接口错误 ${response.status}`);return data.data}
  window.toggleUpload=()=>{const overlay=$('uploadOverlay');if(!overlay)return;overlay.classList.toggle('active');if(overlay.classList.contains('active'))$('manualOrderInput')?.focus()};window.openHomeMenu=()=>{const menu=$('homeMenu');if(menu)menu.style.display=menu.style.display==='block'?'none':'block'};window.goToRouteEdit=()=>{window.location.href='pages/route_edit.html'};window.goToOrderDetail=()=>{const r=currentRoute();window.location.href=`pages/order_detail.html${r?`?route=${encodeURIComponent(r)}`:''}`};window.goToHistory=()=>{window.location.href='pages/history.html'};window.logout=()=>Auth.logout();window.clearManualInput=()=>{if($('manualOrderInput'))$('manualOrderInput').value='';if($('charCount'))$('charCount').textContent='0';parsedOrders=[];pendingMeta={};renderStatus('idle');renderTags([]);window.renderReviewStores?.([])};window.loadExampleData=()=>{const names=baseStores.slice(0,3).map(storeName).filter(Boolean);setOCRText(names.length?names.join('\n'):'江北胡汪洋经销商\n中景隆贸易\n江北重庆兴农');pendingMeta={};renderStatus('idle')};window.pasteFromClipboard=async()=>{try{setOCRText(await navigator.clipboard.readText());pendingMeta=extractLocalMeta($('manualOrderInput')?.value||'')}catch(_){toast('无法读取剪贴板，请手动粘贴','warning')}};
  window.parseManualInput=async()=>{try{const text=$('manualOrderInput')?.value||'';if(!text.trim())return toast('请先输入或识别运单文字','warning');renderStatus('loading',0,'正在提取门店并与基准库比对...');const data=await parseOrderText(text);parsedOrders=Array.isArray(data.stores)?data.stores:[];pendingMeta={date:data.date||pendingMeta.date||'',vehicle:data.vehicle||pendingMeta.vehicle||'',totalWeight:data.totalWeight||pendingMeta.totalWeight||'',rawOrderCount:data.rawOrderCount||pendingMeta.rawOrderCount||0,matchedCount:data.matchedCount,newStoreCount:data.newStoreCount,recognizedCount:data.recognizedCount,source:'web-confirm'};renderTags(parsedOrders);window.onOrderParsed?.(data);renderStatus(parsedOrders.length?'success':'error',parsedOrders.length,parsedOrders.length?`解析完成：${parsedOrders.length} 家门店${data.newStoreCount?`，新增 ${data.newStoreCount} 家`:''}`:'没有识别到有效门店');if(data.warning)toast(data.warning,'warning');return parsedOrders}catch(e){parsedOrders=[];window.onOrderParsed?.({stores:[]});renderStatus('error',0,e.message);toast(e.message||'解析失败','warning');error(e.message||'解析失败');return[]}};
  window.triggerUpload=type=>{let input=$('homeUploadInput');if(!input){input=document.createElement('input');input.id='homeUploadInput';input.type='file';input.accept=type==='album'?'image/*':'image/*,.txt,.csv';input.style.display='none';document.body.appendChild(input);input.addEventListener('change',handleUploadFile)}input.value='';input.click()};
  async function handleUploadFile(event){const file=event.target.files?.[0];if(!file)return;renderStatus('loading',0,'正在识别图片文字...');try{if(file.type.startsWith('image/')){toast('正在识别运单图片，请稍候...');const data=await callOCR(file);const rawText=String(data?.rawText??'').replace(/\r\n/g,'\n').replace(/\r/g,'\n').trim();if(!rawText)throw Error('OCR未返回文字，请重新拍摄清晰、完整的运单图片');setOCRText(rawText);pendingMeta={route:data.route||currentRoute(),date:data.date||'',vehicle:data.vehicle||'',totalWeight:data.totalWeight||'',rawOrderCount:data.rawOrderCount||0,source:'ai-ocr'};parsedOrders=[];window.onOrderParsed?.({stores:[]});renderTags([]);renderStatus('success',0,'OCR识别完成：完整原文已写入输入框，请检查后再点击“开始解析”');toast('图片文字已完整提取，请先核对OCR原文');$('manualOrderInput')?.focus();return}if(file.type.startsWith('text/')||/\.csv$/i.test(file.name)){setOCRText(await file.text());pendingMeta=extractLocalMeta($('manualOrderInput')?.value||'');renderStatus('idle',0,'文字已载入，请点击“开始解析”');return}throw Error('暂不支持该文件类型')}catch(e){renderStatus('error',0,e.message||'识别失败');toast(e.message||'运单识别失败','warning');error(e.message||'识别失败')}}
  document.addEventListener('DOMContentLoaded',async()=>{try{if(typeof Auth==='undefined')throw Error('Auth 未加载');if(!(await Auth.checkAuth()))return;await loadBaseStores();await loadServerToday();updateSummary();$('manualOrderInput')?.addEventListener('input',function(){if($('charCount'))$('charCount').textContent=String(this.value.length);parsedOrders=[];window.renderReviewStores?.([])});document.addEventListener('click',event=>{const menu=$('homeMenu'),button=document.querySelector('.menu-btn');if(menu&&menu.style.display==='block'&&!menu.contains(event.target)&&!button?.contains(event.target))menu.style.display='none'})}catch(e){console.error(e);error(e.message||'首页初始化失败')}});
})();
