/* 天友智配One - 运单详情：服务器真实数据 */
(function(){
'use strict';
const $=id=>document.getElementById(id);
let currentRoute='',currentData={orders:[],weight:'',orderBatchId:'',date:'',vehicle:'',route:''};
let historyMode=false;
function currentDate(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
function clean(v){return String(v||'').replace(/[\u3000]/g,' ').replace(/^\s*[\d０-９]+[、.．)）\s-]*/u,'').replace(/\s+/g,' ').trim()}
function key(v){return clean(v).replace(/[\s，,。；;：:（）()【】\[\]<>《》“”"'‘’·-]/g,'').replace(/（临时）|\(临时\)|（20\d{2}）|\(20\d{2}\)/g,'').replace(/谊品鲜/g,'谊品生鲜').replace(/到家/g,'').replace(/客户/g,'客服').replace(/Ⅱ类|II类|Ⅱ類|II類/g,'2类').toLowerCase()}
function baseName(x){return clean(x?.name||x?.storeName||x?.shopName||x?.title||x?.customerName)}
function noteOf(x){return String(x?.note??x?.notes??x?.remark??x?.备注??'').replace(/\s+/g,' ').trim()}
function navOf(x){return String(x?.nav||x?.navigation||x?.url||x?.amap||'').trim()}
function validNav(v){return /^https?:\/\//i.test(String(v||''))}
function normalizeWeight(v){if(v===null||v===undefined||v==='')return '';const s=String(v).trim().replace(/,/g,'');const m=s.match(/[0-9]+(?:\.\d+)?/);if(!m)return '';const n=Number(m[0]);if(!Number.isFinite(n)||n<0)return '';const tons=/吨|\bt\b/i.test(s)?n:/kg|千克|公斤/i.test(s)?n/1000:n>=1000?n/1000:n;if(!Number.isFinite(tons))return '';const fixed=Math.round((tons+Number.EPSILON)*100)/100;return `${fixed.toFixed(2)}t`}
function normalize(raw){if(!Array.isArray(raw))return[];return raw.map((x,i)=>{if(typeof x==='string')return{code:String(i+1).padStart(2,'0'),name:clean(x),nav:'',note:'',weight:0,isNew:false};return{code:String(x?.code||x?.index||i+1).padStart(2,'0'),displayCode:x?.displayCode||'',name:clean(x?.name||x?.storeName||x?.shopName||x?.门店名称),nav:navOf(x),note:noteOf(x),weight:x?.weight,isNew:Boolean(x?.isNew||x?.newStore),matched:x?.matched===true,needsReview:x?.needsReview===true,matchType:x?.matchType||'',matchScore:x?.matchScore??'',candidate:x?.candidate||'',candidates:Array.isArray(x?.candidates)?x.candidates:[],duplicateCount:Number(x?.duplicateCount)||0,rawNames:Array.isArray(x?.rawNames)?x.rawNames:[],status:x?.status||'待配送',orderBatchId:x?.orderBatchId||''}}).filter(x=>x.name)}
function preserveSavedOrder(raw){return normalize(raw).map((x,i)=>({...x,displayCode:x.displayCode||String(i+1).padStart(2,'0')}))}
function authHeaders(){return Auth.getAuthHeaders?Auth.getAuthHeaders():{}}
async function getOrder(date,isHistory,batch){if(isHistory){if(!batch)throw Error('历史记录缺少运单批次');const r=await fetch(`/api/history?date=${encodeURIComponent(date)}`,{cache:'no-store',headers:authHeaders(),credentials:'same-origin'});if(!r.ok)throw Error(`历史数据服务不可用（${r.status}）`);const payload=await r.json(),records=Array.isArray(payload)?payload:(Array.isArray(payload?.data)?payload.data:[]);return records.find(x=>x?.orderBatchId===batch)||null}const query=new URLSearchParams({date});if(batch)query.set('orderBatchId',batch);const r=await fetch(`/api/orders?${query}`,{cache:'no-store',headers:authHeaders(),credentials:'same-origin'});if(!r.ok)throw Error(`当日订单服务不可用（${r.status}）`);const d=await r.json();return d?.today||null}
function readOrderHandoff(date,batch){try{const raw=sessionStorage.getItem('zsp_order_handoff_v1');if(!raw)return null;const item=JSON.parse(raw);const user=typeof Auth!=='undefined'?(Auth.serverUser||{}):{};const userId=String(user.id||user.username||user.account||'').trim();if(!item?.order||item?.date!==date||item?.orderBatchId!==batch||String(item.userId||'')!==userId)return null;if(Date.now()-Number(item.createdAt||0)>120000){sessionStorage.removeItem('zsp_order_handoff_v1');return null}return item.order}catch(_){return null}}
async function load(options={}){const p=new URLSearchParams(location.search);historyMode=p.get('mode')==='history';const date=p.get('date')||currentDate(),batch=p.get('orderBatchId')||p.get('batch')||'';const handoff=options.allowHandoff!==false&&!historyMode?readOrderHandoff(date,batch):null;const t=handoff||await getOrder(date,historyMode,batch);if(!t||!Array.isArray(t.orders))return{orders:[],weight:'',orderBatchId:t?.orderBatchId||batch,date:t?.date||date,vehicle:t?.vehicle||'',route:currentRoute,uniqueStoreCount:0};let orders=preserveSavedOrder(t.orders);
  // 服务器保存时已经完成去重、匹配与线路排序；详情页只负责展示，不能再次按当前基准库重算。
  // 这样可保证“确认录入 → 今日运单 → 订单详情”显示的是同一份服务器真实订单。
  return{orders,weight:normalizeWeight(t.totalWeight??t.weight??t.goodsWeight??''),orderBatchId:t.orderBatchId||batch,date:t.date||date,vehicle:t?.vehicle||'',route:currentRoute,uniqueStoreCount:Number(t.uniqueStoreCount)||orders.length}}
function render(a,w){const n=Number(currentData.uniqueStoreCount)||a.length,nn=a.filter(x=>x.isNew).length,rr=a.filter(x=>x.needsReview).length;if($('storeCount'))$('storeCount').textContent=rr||nn?`${rr?`⚠️ 待确认${rr}家、`:''}${nn?`新增${nn}家、`:''}总${n}家`:`${n}家`;if($('totalWeight'))$('totalWeight').textContent=normalizeWeight(w)||'0t';const box=$('routeList');if(!box)return;box.innerHTML='';if(!a.length){box.innerHTML='<div class="empty-tip"><span class="icon">📭</span>暂无配送数据</div>';return}a.forEach((s,i)=>{const row=document.createElement('div');row.className='store-item';const idx=document.createElement('span');idx.className='store-index';idx.textContent=`${String(i+1).padStart(2,'0')}、`;const content=document.createElement('div');content.className='store-content';const name=document.createElement('div');name.className='store-name';if(s.isNew){const marker=document.createElement('span');marker.className='new-marker';marker.textContent='⚠ 新增';name.append(marker,document.createTextNode(` ${s.name}`))}else if(s.needsReview){const marker=document.createElement('span');marker.className='new-marker';marker.textContent='⚠ 待确认';name.append(marker,document.createTextNode(` ${s.name}`))}else{name.textContent=s.name}if(validNav(s.nav)){name.classList.add('is-navigable');name.title='点击打开导航';name.addEventListener('click',()=>{hidePopups();location.href=s.nav})}content.appendChild(name);if(s.needsReview&&s.candidate){const review=document.createElement('div');review.className='store-note';review.textContent=`建议匹配：${s.candidate}`;content.appendChild(review)}if(s.note){const note=document.createElement('div');note.className='store-note';note.textContent=s.note;content.appendChild(note)}row.append(idx,content);box.appendChild(row)})}
function header(){if($('routeName'))$('routeName').textContent=currentRoute;if($('menuRoute'))$('menuRoute').textContent=currentRoute;if($('todayDate'))$('todayDate').textContent=currentData.date||currentDate();if($('vehicleText'))$('vehicleText').textContent=currentData.vehicle||'未设置';if($('newVehicle'))$('newVehicle').value=currentData.vehicle||''}
function hidePopups(){const menu=$('menuPanel');if(menu)menu.style.display='none';const dialog=$('vehicleDialog');if(dialog)dialog.style.display='none'}
window.toggleMenu=()=>{const m=$('menuPanel');if(!m)return;m.style.display=m.style.display==='block'?'none':'block'};
window.openVehicle=()=>{if(historyMode)return alert('历史运单不能更换车辆');hidePopups();if($('vehicleDialog'))$('vehicleDialog').style.display='flex'};
window.closeVehicle=()=>hidePopups();
window.saveVehicle=async()=>{if(historyMode)return alert('历史运单不能更换车辆');const v=$('newVehicle')?.value.trim();if(!v)return alert('请输入车辆号码');if(!currentData.orderBatchId)return alert('当前没有服务器订单批次，不能修改车辆');try{const r=await fetch('/api/orders',{method:'POST',headers:{'Content-Type':'application/json',...authHeaders()},credentials:'same-origin',body:JSON.stringify({date:currentData.date,vehicle:v,totalWeight:currentData.weight,orders:currentData.orders,orderBatchId:currentData.orderBatchId,source:'order-detail'})});if(!r.ok)throw Error(`保存失败（${r.status}）`);const d=await r.json();if(!d.success)throw Error(d.error||'保存失败');currentData.vehicle=v;currentData.weight=normalizeWeight(d.data?.totalWeight??currentData.weight);currentData.orders=normalize(d.data?.orders||currentData.orders);currentData.uniqueStoreCount=Number(d.data?.uniqueStoreCount)||currentData.orders.length;header();render(currentData.orders,currentData.weight);alert('车辆已同步到服务器');closeVehicle()}catch(e){alert(`保存失败：${e.message}`)}};
window.shareOrder=async()=>{const a=currentData.orders,n=a.filter(x=>x.isNew).length,r=a.filter(x=>x.needsReview).length,t=Number(currentData.uniqueStoreCount)||a.length,text=`天友智配One\n${currentData.date}\n${currentRoute}\n🚚 ${currentData.vehicle||'未设置'}\n${r?`⚠️ 待确认${r}家、`:''}${n?`新增${n}家、`:''}总${t}家\n总重量 ${normalizeWeight(currentData.weight)||'0t'}`;hidePopups();try{if(navigator.share)await navigator.share({title:'配送记录',text});else{await navigator.clipboard?.writeText(text);alert('📋 已复制')}}catch(_) {}};
window.goBack=()=>{
  hidePopups();
  if(historyMode&&window.history.length>1){
    window.history.back();
    return;
  }
  const referrer=document.referrer||'';
  try{
    const ref=new URL(referrer,location.href);
    if(ref.origin===location.origin&&ref.pathname.endsWith('/home.html')&&window.history.length>1){
      window.history.back();
      return;
    }
  }catch(_){}
  location.href='../home.html';
};
window.logout=()=>{hidePopups();if(confirm('确定退出登录吗？'))Auth.logout()};
async function refreshTodayDetail(){if(historyMode||currentData.date!==currentDate())return;try{const latest=await load();currentData=latest;header();render(currentData.orders,currentData.weight)}catch(e){console.error('刷新当日运单失败',e)}}
document.addEventListener('DOMContentLoaded',async()=>{hidePopups();try{if(typeof Auth==='undefined')throw Error('Auth 未加载');if(!(await Auth.checkAuth()))return;currentRoute=Auth.getCurrentRoute();if(!currentRoute)throw Error('未指定配送线路');currentData.route=currentRoute;const handoff=load({allowHandoff:true});currentData=await handoff;header();render(currentData.orders,currentData.weight);if(!historyMode&&readOrderHandoff(currentData.date,currentData.orderBatchId)){try{const latest=await load({allowHandoff:false});currentData=latest;header();render(currentData.orders,currentData.weight);sessionStorage.removeItem('zsp_order_handoff_v1')}catch(error){console.warn('服务器订单校验失败，保留已保存数据',error)}}document.addEventListener('click',event=>{const menu=$('menuPanel'),button=document.querySelector('.menu-btn');if(menu&&menu.style.display==='block'&&!menu.contains(event.target)&&!button?.contains(event.target))hidePopups()})}catch(e){console.error(e);if($('routeList'))$('routeList').innerHTML=`<div class="empty-tip"><span class="icon">🌐</span>${e.message}<br><small>请联网后重试</small></div>`;if($('storeCount'))$('storeCount').textContent='—';if($('totalWeight'))$('totalWeight').textContent='—'}})
window.addEventListener('pagehide',hidePopups);
window.addEventListener('pageshow',event=>{hidePopups();if(event.persisted&&typeof Auth!=='undefined')refreshTodayDetail()});
})();
