/* 天友智配One - 今日运单详情
 * T1：页面只展示服务器真实数据；localStorage 仅保存会话/临时UI状态。
 */
(function(){
'use strict';
const $=id=>document.getElementById(id);
let currentData={orders:[],weight:'',orderBatchId:'',date:'',vehicle:'',route:''};
function systemToday(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function clean(v){return String(v||'').replace(/[\u3000]/g,' ').replace(/^\s*[\d０-９]+[、.．)）\s-]*/u,'').replace(/\s+/g,' ').trim()}
function weightKg(v){const s=String(v??'').replace(/,/g,'');const m=s.match(/[0-9]+(?:\.[0-9]+)?/);if(!m)return 0;const n=Number(m[0]);return /吨|\bt\b/i.test(s)?n*1000:n}
function key(v){return clean(v).replace(/[\s，,。；;：:（）()【】\[\]<>《》“”"'‘’·-]/g,'').toLowerCase()}
function baseName(x){return clean(x?.name||x?.storeName||x?.shopName||x?.title||x?.customerName)}
function normalizeOrders(raw){if(!Array.isArray(raw))return[];const seen=new Set();return raw.map((x,i)=>typeof x==='string'?{code:String(i+1).padStart(2,'0'),name:clean(x),nav:'',weight:0,isNew:false}:{code:String(x?.code||x?.index||i+1).padStart(2,'0'),name:clean(x?.name||x?.storeName||x?.shopName||x?.门店名称),nav:String(x?.nav||x?.navigation||x?.url||x?.amap||''),weight:weightKg(x?.weight),isNew:Boolean(x?.isNew||x?.newStore),status:x?.status||'待配送',orderBatchId:x?.orderBatchId||''}).filter(x=>x.name&&!seen.has(key(x.name))&&(seen.add(key(x.name)),true))}
function sortByBase(raw,base){const src=normalizeOrders(raw),bs=(Array.isArray(base)?base:[]).map((x,i)=>({raw:x,name:baseName(x),idx:i,code:String(x?.code||i+1).padStart(2,'0'),nav:String(x?.nav||x?.navigation||x?.url||x?.amap||'')}));if(!bs.length)return src.map((x,i)=>({...x,displayCode:String(i+1).padStart(2,'0')}));const used=new Set(),matched=[],news=[];src.forEach(o=>{const k=key(o.name);let hit=-1;for(let i=0;i<bs.length;i++){if(used.has(i))continue;if(k===key(bs[i].name)){hit=i;break}}if(hit>=0){used.add(hit);const b=bs[hit];matched.push({...o,code:b.code,displayCode:b.code,name:b.name||o.name,nav:b.nav||o.nav,isNew:false,_base:hit})}else news.push({...o,isNew:true})});matched.sort((a,b)=>a._base-b._base);news.forEach((x,i)=>x.displayCode=`N${String(i+1).padStart(2,'0')}`);return matched.concat(news).map(x=>{const y={...x};delete y._base;return y})}
async function loadBase(route){const r=await fetch(`/api/routes?route=${encodeURIComponent(route)}`,{cache:'no-store',headers:Auth.getAuthHeaders?Auth.getAuthHeaders():{}});if(!r.ok)throw new Error(r.status===401?'登录已失效':`基准数据读取失败（${r.status}）`);const d=await r.json();const stores=Array.isArray(d)?d:(d?.stores||d?.data||[]);if(!Array.isArray(stores))throw new Error('基准数据库格式错误');return stores}
async function load(){const route=Auth.getCurrentRoute();if(!route)throw new Error('未绑定线路');const date=systemToday();const headers=Auth.getAuthHeaders?Auth.getAuthHeaders():{};const r=await fetch(`/api/orders?date=${encodeURIComponent(date)}`,{cache:'no-store',headers});if(!r.ok)throw new Error(r.status===401?'登录已失效，请重新登录':`今日订单服务不可用（${r.status}）`);const d=await r.json();const t=d?.today||null;if(!t||!Array.isArray(t.orders))return{orders:[],weight:'',orderBatchId:'',date,vehicle:'',route};const base=await loadBase(route);const orders=sortByBase(t.orders,base);return{orders,weight:t.totalWeight??'',orderBatchId:t.orderBatchId||'',date:t.date||date,vehicle:t.vehicle||'',route:t.route||route}}
function render(orders,totalWeight){const total=orders.length,newCount=orders.filter(x=>x.isNew).length;if($('storeCount'))$('storeCount').textContent=newCount?`⚠️ 新${newCount}家、总${total}家`:`${total}家`;const w=weightKg(totalWeight)||orders.reduce((s,x)=>s+weightKg(x.weight),0);if($('totalWeight'))$('totalWeight').textContent=`${Number(w.toFixed(3))} kg`;const box=$('routeList');if(!box)return;box.innerHTML='';if(!orders.length){box.innerHTML='<div class="empty-tip"><span class="icon">📭</span>今日暂无配送数据</div>';return}orders.forEach((s,i)=>{const row=document.createElement('div');row.className='store-item';const idx=document.createElement('span');idx.className='store-index';idx.textContent=`${s.displayCode||s.code||String(i+1).padStart(2,'0')}、`;const name=document.createElement('span');name.className='store-name';name.textContent=s.isNew?`⚠️ 新增 ${s.name}`:s.name;const nav=document.createElement('button');nav.className='nav-btn';nav.type='button';nav.textContent='导航';nav.onclick=()=>s.nav?location.href=s.nav:alert('该门店暂无导航地址');row.append(idx,name,nav);box.appendChild(row)})}
function initHeader(){const route=currentData.route||Auth.getCurrentRoute();if($('routeName'))$('routeName').textContent=route||'未选择线路';if($('menuRoute'))$('menuRoute').textContent=route||'未选择线路';if($('todayDate'))$('todayDate').textContent=currentData.date||systemToday();if($('vehicleText'))$('vehicleText').textContent=currentData.vehicle||'未设置';if($('newVehicle'))$('newVehicle').value=currentData.vehicle||'')}
window.toggleMenu=()=>{const m=$('menuPanel');if(m)m.style.display=m.style.display==='block'?'none':'block'};
window.openVehicle=()=>{if($('vehicleDialog'))$('vehicleDialog').style.display='flex';if($('menuPanel'))$('menuPanel').style.display='none'};
window.closeVehicle=()=>{if($('vehicleDialog'))$('vehicleDialog').style.display='none'};
window.saveVehicle=async()=>{const v=$('newVehicle')?.value.trim();if(!v)return alert('请输入车辆号码');if(!currentData.orderBatchId)return alert('当前没有服务器订单批次，不能修改车辆');try{const r=await fetch('/api/orders',{method:'POST',headers:{'Content-Type':'application/json',...(Auth.getAuthHeaders?Auth.getAuthHeaders():{})},body:JSON.stringify({route:currentData.route,date:currentData.date,vehicle:v,totalWeight:currentData.weight,orders:currentData.orders,orderBatchId:currentData.orderBatchId,source:'order-detail'})});if(!r.ok)throw new Error(`保存失败（${r.status}）`);const d=await r.json();if(!d.success)throw new Error(d.error||'保存失败');currentData.vehicle=v;currentData.weight=d.data?.totalWeight??currentData.weight;initHeader();alert('车辆已同步到服务器');window.closeVehicle()}catch(e){alert(`保存失败：${e.message}`)}};
window.shareOrder=async()=>{const o=currentData.orders||[],n=o.filter(x=>x.isNew).length,t=o.length,text=`天友智配One\n${currentData.date}\n${currentData.route}\n🚚 ${currentData.vehicle||'未设置'}\n${n?`⚠️ 新${n}家、总${t}家`:`${t}家`}\n总重量 ${$('totalWeight')?.textContent||'0 kg'}`;try{if(navigator.share)await navigator.share({title:'今日运单',text});else{await navigator.clipboard?.writeText(text);alert('📋 运单信息已复制')}}catch(_){}};
window.goBack=()=>{location.href='../home.html'};window.logout=()=>{if(confirm('确定退出登录吗？'))Auth.logout()};
document.addEventListener('DOMContentLoaded',async()=>{try{if(window.Auth&&!Auth.checkAuth())return;currentData=await load();initHeader();render(currentData.orders,currentData.weight)}catch(e){console.error(e);if($('routeList'))$('routeList').innerHTML=`<div class="empty-tip"><span class="icon">🌐</span>${e.message}<br><small>请联网后重试</small></div>`;if($('storeCount'))$('storeCount').textContent='—';if($('totalWeight'))$('totalWeight').textContent='—'}})
})();
