// js/admin/user_manage.js
// 用户管理模块
let currentUserEditId = null;
function openUserManagement(){openDialog('userDialog');renderUsers();}
async function renderUsers(filter=''){let users=await Auth.getUsers();users.sort((a,b)=>a.role==='admin'?-1:b.role==='admin'?1:(a.id||0)-(b.id||0));if(filter)users=users.filter(u=>String(u.name||'').includes(filter)||String(u.route||'').includes(filter)||String(u.role||'').includes(filter));const c=document.getElementById('userList');if(!users.length){c.innerHTML='<div class="admin-empty">暂无用户</div>';return}const rm={admin:'管理员',driver:'司机',delivery:'配送'},rc={admin:'admin',driver:'driver',delivery:'delivery'};c.innerHTML=users.map(u=>`<div class="admin-list-item"><div class="info"><div class="name">${u.name||'(未命名)'}</div><div class="sub">${u.route||'管理员'} · <span class="role-badge ${rc[u.role]||'driver'}">${rm[u.role]||'司机'}</span></div></div><div class="actions"><button class="edit-btn" onclick="editUser(${u.id})">编辑</button>${u.role==='admin'?'':`<button class="del-btn" onclick="deleteUser(${u.id})">删除</button>`}</div></div>`).join('');}
function filterUsers(){renderUsers(document.getElementById('userSearch').value.trim())}
function showAddUserForm(){currentUserEditId=null;document.getElementById('userFormTitle').textContent='添加用户';document.getElementById('userFormName').value='';document.getElementById('userFormRoute').value='';document.getElementById('userFormRole').value='driver';openDialog('userFormDialog')}
function editUser(id){Auth.getUsers().then(users=>{const u=users.find(x=>x.id===id);if(!u)return;currentUserEditId=id;if(u.role==='admin'){document.getElementById('adminEditTitle').textContent='修改管理员信息';document.getElementById('adminEditName').value=u.name||'';document.getElementById('adminEditPassword').value='';document.getElementById('adminEditUnifiedPassword').value='';openDialog('adminEditDialog')}else{document.getElementById('userEditTitle').textContent='编辑用户';document.getElementById('userEditName').value=u.name||'';document.getElementById('userEditRoute').value=String(u.route||'').replace('号线','');document.getElementById('userEditRole').value=u.role||'driver';openDialog('userEditDialog')}})}
async function saveUser(){const name=document.getElementById('userFormName').value.trim(),raw=document.getElementById('userFormRoute').value.trim(),role=document.getElementById('userFormRole').value;if(!raw)return showToast('请填写线路编号','error');const route=formatRouteCode(raw);if(!route)return showToast('请输入有效数字','error');if(await Auth.isRouteRegistered(route))return showToast('该线路已存在用户','error');const u=await Auth.createUser(route,getUnifiedPassword(),role,name);if(u){showToast('用户已添加');closeDialog('userFormDialog');renderUsers()}else showToast('用户添加失败，请重试','error')}
async function saveUserEdit(){const name=document.getElementById('userEditName').value.trim(),raw=document.getElementById('userEditRoute').value.trim(),role=document.getElementById('userEditRole').value;if(!raw)return showToast('请填写线路编号','error');const route=formatRouteCode(raw),users=await Auth.getUsers(),i=users.findIndex(u=>u.id===currentUserEditId);if(!route||i<0)return showToast('用户不存在或线路无效','error');if(users.some(u=>u.route===route&&u.id!==currentUserEditId))return showToast('该线路已存在用户','error');users[i]={...users[i],name:name||users[i].name||'',route,role};await Auth.saveUsers(users);showToast('用户已更新');closeDialog('userEditDialog');renderUsers()}
async function saveAdminEdit(){const name=document.getElementById('adminEditName').value.trim(),adminPassword=document.getElementById('adminEditPassword').value.trim(),unified=document.getElementById('adminEditUnifiedPassword').value.trim();const users=await Auth.getUsers(),i=users.findIndex(u=>u.id===currentUserEditId);if(i<0)return showToast('用户不存在','error');if(name)users[i].name=name;if(adminPassword)users[i].password=adminPassword;if(unified){if(unified.length<6)return showToast('统一密码至少6位','error');if(!confirm('确定将全部普通用户密码更新为该统一密码吗？'))return;try{const r=await fetch('/api/users-unified-password',{method:'POST',headers:Auth.getAuthHeaders({'Content-Type':'application/json'}),body:JSON.stringify({password:unified})});const d=await r.json();if(!r.ok||!d.success)throw Error(d.error||'更新失败');localStorage.setItem('unified_password',unified);showToast(d.message||'全部普通用户密码已更新');}catch(e){showToast(e.message,'error');return}}if(name||adminPassword){await Auth.saveUsers(users)}DB.addLog('管理员编辑',`编辑管理员: ${name||'管理员'}${unified?'，更新全部普通用户密码':''}`);closeDialog('adminEditDialog');renderUsers()}
async function deleteUser(id){const users=await Auth.getUsers(),u=users.find(x=>x.id===id);if(!u)return;if(u.role==='admin')return showToast('管理员账户不可删除','warning');if(!confirm('确定删除该用户吗？'))return;await Auth.saveUsers(users.filter(x=>x.id!==id));showToast('用户已删除','warning');renderUsers()}
function toggleAdminEditPassword(){const p=document.getElementById('adminEditPassword');p.type=p.type==='password'?'text':'password'}function toggleAdminEditUnifiedPassword(){const p=document.getElementById('adminEditUnifiedPassword');p.type=p.type==='password'?'text':'password'}
window.openUserManagement=openUserManagement;window.renderUsers=renderUsers;window.filterUsers=filterUsers;window.showAddUserForm=showAddUserForm;window.editUser=editUser;window.saveUser=saveUser;window.saveUserEdit=saveUserEdit;window.saveAdminEdit=saveAdminEdit;window.deleteUser=deleteUser;window.toggleAdminEditPassword=toggleAdminEditPassword;window.toggleAdminEditUnifiedPassword=toggleAdminEditUnifiedPassword;
