// functions/api/ocr.js
// 天友智配One：运单图片 → AI识别 → 提取日期/车牌/重量/门店 → 基准排序 → 新增门店置底
export async function onRequest(context){const{request,env}=context;if(request.method!=='POST')return json({success:false,error:'Method not allowed'},405);try{const body=await request.json(),image=body?.image,route=formatRoute(body?.route);if(!image||!route)return json({success:false,error:'缺少运单图片或线路'},400);if(!env.AI||typeof env.AI.run!=='function')return json({success:false,error:'Cloudflare Workers AI 未绑定，请配置 AI Binding'},500);const parsed=parseAIResponse(await runAI(env.AI,image)),base=await getBaseStores(env,route),result=normalizeAndSort(parsed.stores,base);if(!result.stores.length)return json({success:false,error:'AI未能从运单中识别出有效门店，请重新上传清晰截图'},422);return json({success:true,data:{route,date:parsed.date||'',vehicle:normalizeVehicle(parsed.vehicle),totalWeight:normalizeWeight(parsed.totalWeight),rawOrderCount:parsed.rawOrderCount||0,stores:result.stores,storeCount:result.stores.length,recognizedCount:result.recognizedCount,matchedCount:result.matchedCount,newStoreCount:result.newStoreCount,warning:result.newStoreCount?`发现 ${result.newStoreCount} 家新增门店，请核对`:''}})}catch(e){console.error('OCR error:',e);return json({success:false,error:e?.message||'运单图片处理失败'},500)}}
async function runAI(AI,imageInput){const bytes=decodeImageBase64(imageInput);if(!bytes.length)throw new Error('图片数据无效或无法解码');if(!isSupportedImage(bytes))throw new Error('无法识别手机截图图片格式，请使用 PNG、JPG 或 WebP');const prompt=`你是天友乳业配送运单识别助手。请读取整张手机截图，严格按图片文字识别，不要猜测，不要补充图片不存在的信息。\n\n必须提取：\n1. 运输日期，例如2026-08-22。\n2. 车牌号，例如渝DK7692。\n3. 承运订单区域明确写出的总重量，例如1.806213t。总数量207不是门店数量。\n4. 承运订单下面的门店路线。门店通常以 -> 连接，例如 A -> B -> C。每一个箭头分隔出的完整客户名称都是一家门店。\n\n只返回完整JSON，不要Markdown，不要解释：\n{"date":"2026-08-22","vehicle":"渝DK7692","rawOrderCount":207,"totalWeight":"1.806213t","stores":["A","B","C"]}\n\n规则：\n- stores只放实际配送客户/门店，每家一个数组元素。\n- “总数量”“总重量”“总体积”“订单编号”“司机”“送货员”“车牌”“日期”等都不能作为门店。\n- 优先读取“承运订单”区域；不要把整条A -> B -> C当成一个门店。\n- 保留门店完整名称，包括区域、编号、公司名和括号内容。\n- 同名门店重复出现时只保留一次；相似但不确定是否同一家时不要合并。\n- rawOrderCount只记录“总数量”的数字，它不是门店数。\n- totalWeight只记录“总重量”的原始数值和单位。\n- JSON必须完整闭合。`;return AI.run('@cf/llava-hf/llava-1.5-7b-hf',{prompt,image:Array.from(bytes),max_tokens:4096,temperature:0.01})}
function decodeImageBase64(input){let v=String(input||'').trim(),comma=v.indexOf(',');if(v.startsWith('data:')&&comma>=0)v=v.slice(comma+1);v=v.replace(/\s/g,'');try{const b=atob(v),a=new Uint8Array(b.length);for(let i=0;i<b.length;i++)a[i]=b.charCodeAt(i);return a}catch(e){throw new Error('图片Base64数据损坏，无法解码')}}
function isSupportedImage(b){return(b.length>=8&&b[0]===137&&b[1]===80&&b[2]===78&&b[3]===71)||(b.length>=3&&b[0]===255&&b[1]===216&&b[2]===255)||(b.length>=12&&b[0]===82&&b[1]===73&&b[2]===70&&b[3]===70&&b[8]===87&&b[9]===69&&b[10]===66&&b[11]===80)}
function extractAIText(r){if(typeof r==='string')return r;if(!r||typeof r!=='object')return '';return String(r.description??r.response??r.text??r.result?.description??r.result?.response??r.result?.text??'')}
function parseAIResponse(r){const s=extractAIText(r).trim(),c=[];const f=s.match(/```(?:json)?\s*([\s\S]*?)\s*```/i);if(f)c.push(f[1]);c.push(s);const a=s.indexOf('{'),z=s.lastIndexOf('}');if(a>=0&&z>a)c.push(s.slice(a,z+1));for(const x of c){try{const d=JSON.parse(x);if(d&&Array.isArray(d.stores))return{stores:expandStoreList(d.stores),date:d.date||'',vehicle:d.vehicle||'',totalWeight:d.totalWeight||'',rawOrderCount:Number(d.rawOrderCount)||0}}catch(_){}}return extractFallback(s)}
function expandStoreList(items){const out=[];for(const item of items||[]){const v=typeof item==='string'?item:item?.name||item?.storeName||item?.customerName||'';splitStoreChain(v).forEach(x=>{const n=cleanStoreName(x);if(n)out.push(n)})}return unique(out)}
function splitStoreChain(v){return String(v||'').replace(/→|＞|》|➜|➤|⇒/g,'->').split(/\s*(?:->|-->)\s*/).map(x=>x.trim()).filter(Boolean)}
function extractFallback(text){const s=String(text||'').replace(/\r/g,'\n'),stores=[];const chains=s.match(/[^\n{}]{2,}(?:\s*(?:->|→|〉|》|➜)\s*[^\n{}]{2,})+/g)||[];chains.forEach(c=>splitStoreChain(c).forEach(p=>{const n=cleanStoreName(p);if(isLikelyStore(n))stores.push(n)}));const weight=s.match(/(?:总重量|重量|合计重量|总计)\s*[:：]?\s*([\d]+(?:\.\d+)?)\s*(kg|KG|千克|公斤|吨|t)?/i),plate=s.match(/(?:车牌号|车牌|车辆)\s*[:：]?\s*([\u4e00-\u9fa5][A-Z0-9]{5,7})/i),date=s.match(/(20\d{2}[-/.年]\d{1,2}[-/.月]\d{1,2}日?)/),count=s.match(/总数量\s*[:：]?\s*(\d+)/);return{stores:unique(stores),totalWeight:weight?`${weight[1]}${weight[2]||'kg'}`:'',vehicle:plate?plate[1]:'',date:date?normalizeDate(date[1]):'',rawOrderCount:count?Number(count[1]):0}}
function isLikelyStore(v){if(!v||v.length<3||v.length>150)return false;if(/总重量|总数量|总体积|订单编号|运单编号|车牌|车辆|运输日期|日期|司机|送货员|主司机|承运订单|额定装载|额定载重|额定体积|总计|合计|单价|金额/.test(v))return false;return /店|公司|经销商|加盟|工厂|中心|超市|便利|生鲜|食品|贸易|供应链|商行|门市|乳业|大厦|药房|餐饮|酒店/.test(v)}
async function getBaseStores(env,route){const url=env.UPSTASH_REDIS_REST_URL,token=env.UPSTASH_REDIS_REST_TOKEN;if(!url||!token)return[];try{const r=await fetch(`${url}/get/${encodeURIComponent(`route:${route}`)}`,{headers:{Authorization:`Bearer ${token}`}});if(!r.ok)return[];const d=await r.json();let p=null;if(d?.result){try{p=typeof d.result==='string'?JSON.parse(d.result):d.result}catch(_){}}return Array.isArray(p?.stores)?p.stores:[]}catch(_){return[]}}
function normalizeBase(s,i){if(typeof s==='string')return{name:cleanStoreName(s),code:String(i+1).padStart(2,'0'),nav:'',index:i};if(!s)return null;const name=cleanStoreName(s.name||s.storeName||s.title||s.customerName||'');return name?{name,code:String(s.code||i+1).padStart(2,'0'),nav:s.nav||s.navigation||s.url||'',index:i}:null}
function matchKey(s){return cleanStoreName(s).replace(/[\s\u3000，,。；;：:（）()【】\[\]<>《》“”"'‘’·]/g,'').toLowerCase()}
function normalizeAndSort(recognized,baseStores){const src=unique((recognized||[]).map(cleanStoreName).filter(Boolean)),base=(baseStores||[]).map(normalizeBase).filter(Boolean);if(!base.length)return{stores:src.map((name,i)=>({code:String(i+1).padStart(2,'0'),name,nav:'',isNew:false,matched:false})),recognizedCount:src.length,matchedCount:0,newStoreCount:0};const matched=[],news=[],used=new Set();src.forEach(raw=>{const rk=matchKey(raw);let best=null,score=0;base.forEach(b=>{if(used.has(b.index))return;const bk=matchKey(b.name);if(rk===bk){best=b;score=1;return}if(rk.length>8&&bk.length>8&&(rk.includes(bk)||bk.includes(rk))&&score<0.93){best=b;score=0.93}});if(best&&score>=0.93){used.add(best.index);matched.push({code:best.code,name:best.name,nav:best.nav||'',isNew:false,matched:true,_baseIndex:best.index})}else news.push({code:'',name:raw,nav:'',isNew:true,matched:false})});matched.sort((a,b)=>a._baseIndex-b._baseIndex);news.forEach((x,i)=>x.code=`N${String(i+1).padStart(2,'0')}`);const stores=matched.concat(news).map(x=>{const y={...x};delete y._baseIndex;return y});return{stores,recognizedCount:src.length,matchedCount:matched.length,newStoreCount:news.length}}
function cleanStoreName(v){return String(v||'').replace(/^[\s\d]+[、.．)）-]+/,'').replace(/\s+/g,' ').trim()}
function unique(a){const s=new Set();return a.filter(x=>{const k=matchKey(x);if(!k||s.has(k))return false;s.add(k);return true})}
function normalizeWeight(v){if(v===null||v===undefined||v==='')return '';const s=String(v).trim(),m=s.match(/[\d]+(?:\.\d+)?/);if(!m)return '';const n=Number(m[0]);return/吨|\bt\b/i.test(s)?`${n}t`:`${n}kg`}
function normalizeVehicle(v){return String(v||'').replace(/[\s>]+$/,'').trim()}
function normalizeDate(v){const s=String(v||'').trim().replace(/[年月]/g,'-').replace(/日/g,'').replace(/\//g,'-').replace(/\./g,'-'),m=s.match(/(20\d{2})-(\d{1,2})-(\d{1,2})/);return m?`${m[1]}-${String(m[2]).padStart(2,'0')}-${String(m[3]).padStart(2,'0')}`:s}
function formatRoute(v){return String(v||'').trim()}
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json;charset=UTF-8','Cache-Control':'no-store'}})}