// functions/api/users.js
// 管理员用户管理 API：真实读取/写入 Upstash admin_users。
// Redis 永远只保存 passwordHash；环境变量中的初始密码仅用于首次初始化。
import { authRequired } from './_auth.js';
import { hashPassword, isPasswordHash } from './_password.js';
const REDIS_KEY='admin_users';

function defaultUsers(env){return[
{id:1,name:String(env.DEFAULT_ADMIN_NAME||'tianbo').trim(),route:'',role:'admin',initialPassword:String(env.DEFAULT_ADMIN_PASSWORD||''),createdAt:'2026-08-25T00:00:00.000Z'},
{id:17,name:'17号线',route:'17号线',role:'driver',initialPassword:String(env.DEFAULT_DRIVER_PASSWORD||''),createdAt:'2026-08-25T00:00:00.000Z'}
].filter(u=>u.initialPassword)}

export async function onRequest(context){const{request,env}=context,method=request.method,URL=env.UPSTASH_REDIS_REST_URL,TOKEN=env.UPSTASH_REDIS_REST_TOKEN;if(!URL||!TOKEN)return json({error:'Redis not configured'},500);const session=await authRequired(request,env,{admin:true});if(!session)return json({error:'管理员登录已失效或无权限'},401);try{let users=await readUsers(URL,TOKEN);const seeded=await ensureDefaultUsers(users,env);if(seeded.changed){users=seeded.users;await saveUsers(URL,TOKEN,users)}if(method==='GET')return json({success:true,users:sanitizeUsers(users)});if(method==='POST'){const body=await request.json().catch(()=>({}));if(!Array.isArray(body.users))return json({error:'users 必须是数组'},400);const byId=new Map(users.map(u=>[String(u?.id),u])),byRoute=new Map(users.filter(u=>normalizeRoute(u?.route)).map(u=>[normalizeRoute(u?.route),u])),merged=[];for(const input of body.users){const old=byId.get(String(input?.id))||byRoute.get(normalizeRoute(input?.route));const user={...(old||{}),...(input||{})};if(!user.id||!String(user.name||'').trim())return json({error:'用户ID和用户名不能为空'},400);user.name=String(user.name).trim();user.role=user.role==='admin'?'admin':'driver';user.route=normalizeRoute(user.route);if(Object.prototype.hasOwnProperty.call(input||{},'password')){const plain=String(input.password||'');if(plain)user.passwordHash=await hashPassword(plain);delete user.password}else if(!isPasswordHash(user.passwordHash)){if(old?.password)user.passwordHash=await hashPassword(String(old.password));else if(!user.passwordHash)delete user.password;delete user.password}if(!user.sessionVersion)user.sessionVersion=Number(old?.sessionVersion||1);if(!old)user.createdAt=user.createdAt||new Date().toISOString();merged.push(user)}const owners=new Map();for(const user of merged){if(user.role==='admin'||!user.route)continue;const key=normalizeRoute(user.route);if(owners.has(key))return json({error:`线路 ${key} 已绑定多个用户`},409);owners.set(key,user.id)}for(const required of defaultUsers(env)){if(!merged.some(u=>u&&(String(u.id)===String(required.id)||normalizeRoute(u.route)===normalizeRoute(required.route))&&u.role===required.role)){const{initialPassword,...meta}=required;merged.push({...meta,passwordHash:await hashPassword(initialPassword),sessionVersion:1})}}const finalUsers=merged.map(user=>{const old=byId.get(String(user.id));if(!old)return user;const changed=String(old.passwordHash||old.password||'')!==String(user.passwordHash||user.password||'')||String(old.role||'driver')!==String(user.role||'driver')||normalizeRoute(old.route)!==normalizeRoute(user.route)||String(old.name||'')!==String(user.name||'');return changed?{...user,sessionVersion:Number(old.sessionVersion||1)+1}:user});await saveUsers(URL,TOKEN,finalUsers);return json({success:true,users:sanitizeUsers(finalUsers)})}return json({error:'Method not allowed'},405)}catch(e){console.error('users api error',e);return json({error:'用户数据服务不可用'},503)}}

async function readUsers(url,token){const r=await fetch(`${url}/get/${REDIS_KEY}`,{headers:{Authorization:`Bearer ${token}`},cache:'no-store'});if(!r.ok)throw Error('Upstash request failed');const d=await r.json();if(!d.result)return[];try{const u=JSON.parse(d.result);return Array.isArray(u)?u:[]}catch{return[]}}
async function saveUsers(url,token,users){const r=await fetch(`${url}/set/${REDIS_KEY}`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify(JSON.stringify(users)),cache:'no-store'});if(!r.ok)throw Error('保存用户失败');const d=await r.json().catch(()=>({}));if(d.result!==undefined&&d.result!=='OK')throw Error('保存用户未确认')}

async function ensureDefaultUsers(users,env){const list=Array.isArray(users)?[...users]:[];let changed=false;for(const required of defaultUsers(env)){const i=list.findIndex(u=>String(u?.id)===String(required.id)||normalizeRoute(u?.route)===normalizeRoute(required.route));if(i<0){const{initialPassword,...meta}=required;list.push({...meta,passwordHash:await hashPassword(initialPassword),sessionVersion:1});changed=true;continue}if(!isPasswordHash(list[i].passwordHash)&&list[i].password){list[i]={...list[i],passwordHash:await hashPassword(String(list[i].password)),sessionVersion:Number(list[i].sessionVersion||1)+1};delete list[i].password;changed=true}if(!list[i].passwordHash&&required.initialPassword){list[i]={...list[i],passwordHash:await hashPassword(required.initialPassword),sessionVersion:Number(list[i].sessionVersion||1)+1};changed=true}if(required.id===1&&list[i].role!=='admin'){list[i]={...list[i],role:'admin',sessionVersion:Number(list[i].sessionVersion||1)+1};changed=true}}return{users:list,changed}}
function normalizeRoute(v){const s=String(v||'').trim(),m=s.match(/^(?:([0-9]+)|([0-9]+)号线)$/);return m?`${String(parseInt(m[1]||m[2],10)).padStart(2,'0')}号线`:s}
function sanitizeUsers(users){return users.map(user=>{const{password,passwordHash,initialPassword,...safe}=user||{};return safe})}
function json(p,status=200){return new Response(JSON.stringify(p),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'}})}